variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

# resources:
#   containers:
#   - container: my_container
#     image: node:latest
#   - container: nginx
#     image: nginx:latest


# pool: Default

# pool:
#     vmImage: 'ubuntu-latest'
 
# container: my_container
# services:
#   nginx: nginx

# steps:
#   # - script: | 
#   #     curl nginx 
#   - script: |
#       docker ps
#     target: host

#   - script: |
#       cat /etc/hostname
#     target: my_container

#   - script: 
#       cat /etc/hostname
#     target: nginx

# --------------------------------------------------------------------------------------------------

jobs:
  - job: 'Ubuntu'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-latest'
    steps:
      - task: Bash@3
        displayName: unset git auth header
        inputs:
          targetType: inline
          script: |
            set -x
            trap "echo The script is terminated; exit" SIGSEGV
            trap 'if [[ $? -eq 139 ]]; then echo "segfault"; fi' CHLD
            trap 'if [[ $? -eq 128 ]]; then echo "segfault in child command"; exit 139; fi' CHLD

            git clone git@github.com:microsoft/azure-pipelines-tasks.git
            echo "Return code = $?"
