variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    value: true
  - name: passphrase
    value: 4eba4y
  - name: agentName
    value: debian-x64-agent

stages:
- stage: 'Win'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      secureSteps: 'download-secure-file-steps-win.yml'
      pool:
        name: 'win-11-pool'
        demands:
          - Agent.Name -equals $(agentName)
  - job: InstallSSHKey_Windows
    displayName: 'Test InstallSSHKey and powershell'
    pool:
      name: 'win-11-pool'
      demands:
        - Agent.Name -equals $(agentName)
    steps:
    - template: templates/test-install-key-win.yml

  - job: 'TwineAuthenticateWin'
    displayName: 'Test Publishing to Artifacts'
    pool:
      name: 'win-11-pool'
      demands:
        - Agent.Name -equals $(agentName)
    steps:
    - template: src/TwineAuthenticate/twine-authenticate-steps.yml

  - job: 'PublishTestResults'
    displayName: 'Test Publishing test Results'
    pool:
      name: 'win-11-pool'
      demands:
        - Agent.Name -equals $(agentName)
    steps:
    - template: src/maven/test-publish-test-results.yml

- stage: 'WinContainer'
  condition: and(succeeded(), eq(variables.needContainer, 'true'))
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-container-template.yml
    parameters:
      pool:
        name: 'win-11-pool'
        demands:
          - Agent.Name -equals $(agentName)