parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues

jobs:
  - job: 'Ubuntu_1804'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-18.04'
    steps:
      - template: src/docker/templates/docker-test.yml
  
  - job: 'Ubuntu_2004'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    steps:
      - template: src/docker/templates/docker-test.yml
  
  - job: 'Ubuntu_2204'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-22.04'
    steps:
      - template: src/docker/templates/docker-test.yml