variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: 'Debian'
  displayName: Debian
  pool:
    name: 'default'
    demands: 
      - Agent.Name -equals win200
  steps:
    - bash: |
        ls -la
        echo '123'
