# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"
  - name: AZP_75787_ENABLE_NEW_LOGIC_LOG
    value: true
  - name: AZP_75787_ENABLE_NEW_LOGIC
    value: true
  - name: AZP_75787_ENABLE_COLLECT
    value: true
  - name: WindowsContainerImage
    value: 'mcr.microsoft.com/windows/servercore:ltsc2022'
resources:
  containers:
  - container: windows_build_container
    image: $(WindowsContainerImage)
    mountReadOnly:
      externals: true
    # volumes:
    # - c:\obtools_host:c:\obtools_container:ro
    env:
      Use_Isolation: true

jobs:
  - job:
    pool: #'agentvmsspool'
      # name: 'Default'
      vmImage: 'windows-latest'
    steps: 
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '6.x'
        target:
          container: windows_build_container
          commands: restricted

      - task: DotNetCoreCLI@2
        inputs:
          command: test
          projects: >
            $(Build.SourcesDirectory)/src/**/TestConsoleApp.csproj
          publishTestResults: false
          arguments: --no-restore --logger trx --configuration release --collect "Code Coverage" --results-directory $(Build.SourcesDirectory)/src/out/logs/TestResults/
        target:
          container: windows_build_container
          commands: restricted
        displayName: Run Authorization service unit tests (windows_build_container)