parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test 
  - name: allValues
  # - name: AGENT_USE_NODE10
  #   value: true

jobs:
- job: 'Win2019'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'Win2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'Ubuntu_1804'
  pool: 
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-18.04'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'Ubuntu_2004'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-20.04'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'Ubuntu_2204'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-22.04'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'MacOS_Public_Catalina'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-10.15'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'MacOS_Public_BigSur'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-11'
  steps:
  - template: src/go/templates/go-steps.yml

- job: 'MacOS_Public_Monterey'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-12'
  steps:
  - template: src/go/templates/go-steps.yml