# resources:


#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
- name: solutionTarget
  type: string
  default: 'someSolutionTarget'
- name: msBuildArguments
  type: string
  default: ''
- name: binSourcePath
  type: string
  default: ''

variables:
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: agent.diagnostic
    value: true
  - name: sourceDir
    value: $(Build.SourcesDirectory)
  # - name: msBuildArgumentsVar
  #   value: ${{ coalesce(parameters.msBuildArguments, format('-target:{0}', parameters.solutionTarget)) }}
  # - name: binSourcePath
  #   value: ${{ coalesce(parameters.binSourcePath, format('{0}/{1}/bin', variables.sourceDir, parameters.solutionTarget )) }}

jobs:
- job: 'Example'
  pool:
    # name: 'Default'
    vmImage: 'ubuntu-22.04'
  steps:
  - powershell: |
      $TTL = 60
      $ttl = [System.Convert]::ToInt32($TTL)
      $ttl.GetType()
      az login
      az account set --subscribtion "3f56da7f-5953-4018-8ca8-e20dbfa0a7e2"
      az network dns record-set cname create --name MyRecordSet --resource-group v-bobreshev-rg --zone-name www.mysite.com --ttl "60"