# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  # - name: agent.disablelogplugin.TestResultLogPlugin
  #   value: true
  # - name: agent.disablelogplugin.TestFilePublisherPlugin
  #   value: false

# resources:
#   containers:
#   - container: my_container
#     image: node:latest
#   - container: nginx
#     image: nginx:latest


# pool:
#     name: "Default"
 
# container:  ubuntu:18.04
# services:
  # nginx: nginx

# steps:
  # - script: |
  #     cat /etc/hostname
  #     export MY_ENV='test'
  #     mkdir test
  #     touch test/file_example
  # - script: |
  #     cat /etc/hostname
  #     sleep 10
  # - script: |
  #     echo "hello world"
  #     # sleep 100
  #     # ls test

  

# --------------------------------------------------------------------------------------------------

pool:
  # name: Default
  vmImage: ubuntu-latest
jobs:
- job:
  displayName: Npm
  timeoutInMinutes: 30
  steps:
  - script: echo "Test"
  - task: Bash@3
    displayName: Sleep Command
    retryCountOnTaskFailure: 4
    timeoutInMinutes: 10
    inputs:
      targetType: 'inline'
      script: |
        node ./src/nodejs/test.js
  - task: Bash@3
    displayName: Sleep Command
    retryCountOnTaskFailure: 4
    inputs:
      targetType: 'inline'
      script: |
        echo "test 2"