variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: ubuntucontainer
    image: node:latest
    options: --hostname ubuntu-test --name ubuntu-test
  - container: nginx
    image: nginx
    options: --hostname nginx-test --name nginx-test
    ports:
    - 8080:80
    env:
      NGINX_PORT: 80

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'ubuntu-latest'

  container: ubuntucontainer

  steps:
  - script: |
      docker ps
      IP=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx-test`
      echo "##vso[task.setvariable variable=nginx-test-ip;]$IP"
    target: host

  - script: 
      cat /etc/hostname
    target:
        container: nginx
  
  # - script: |
  #     apt get install -y nmap
  #     docker pull instrumentisto/nmap:latest
  #     echo $(agent.containernetwork)
  #     echo $(nginx-test-ip)
  #     echo "docker run --network $(agent.containernetwork) --rm -it instrumentisto/nmap  -v -A $(nginx-test-ip)"
  #     docker run --network $(agent.containernetwork) --rm -it instrumentisto/nmap  -v -A $(nginx-test-ip)
  #   target: host

  - script: |  
      echo "const https = require('http');
          https.get('http://$(nginx-test-ip):8080', (resp) => {
            let data = '';

            // A chunk of data has been received.
            resp.on('data', (chunk) => {
              data += chunk;
            });

            // The whole response has been received. Print out the result.
            resp.on('end', () => {
              console.log(JSON.parse(data).explanation);
            });

          }).on('error', (err) => {
            console.log('Error: ' + err.message);
          });" >> test.js
      node test.js

# - job: example
#   pool: 'Default'
#   container: my_container

#   steps:
#   - script: docker ps
#     target: host

#   - script: cat /etc/hostname
#     target:
#         container: nginx

#   - script: cat /etc/hostname
#     target:
#       container: my_container