variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

jobs:
- job: job1
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - task: CmdLine@2
      inputs:
        failOnStderr: false
        script: |
          cd /nonExistingDirectory
          echo '123'
    - task: CmdLine@2
      inputs:
        failOnStderr: true
        script: |
          cd /nonExistingDirectory
          echo '123'
    - script: |
        cd /nonExistingDirectory
        echo '123'
      # continueOnError: true
    - script: echo 'second Step'
