variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources 
    value: true
  - name: DisableCFSDetector
    value: true 
  - name: DisableDockerDetector
    value: true 
  - name: NugetSecurityAnalysisWarningLevel
    value: 'none'
  - name: PythonMultiFeedWarnLevel
    value: 'none'
  - name: passphrase
    value: 4eba4y
  - name: agentName
    value: mac-mini-arm
  - name: poolName
    value: default

stages:
- stage: 'Win'
  dependsOn: []
  jobs:
  - job: UseNodeV1
    displayName: 'Test UseNodeV1 Task'
    pool:
      name: $(poolName)
      demands:
        - Agent.Name -equals $(agentName)
    strategy:
      matrix:
        Node10:
          node.version: '10.x'
        Node12:
          node.version: '12.x'
        Node14:
          node.version: '14.x'
        Node16:
          node.version: '16.x'
    steps:
    - template: src/node/templates/node-toolcache-steps.yml
      parameters:
        nodeVersion: $(node.version)
  - job: NodeTools
    displayName: 'Test NodeTools Task'
    pool:
      name: $(poolName)
      demands:
        - Agent.Name -equals $(agentName)
    strategy:
      matrix:
        Node10:
          node.version: '11.x'
        Node12:
          node.version: '13.x'
        Node14:
          node.version: '8.x'
        Node16:
          node.version: '16.x'
    steps:
    - template: src/node/templates/node-toolcache-nodetool-step.yml
      parameters:
        nodeVersion: $(node.version)