variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: true

jobs:
- job: 'Debian'
  displayName: Debian
  pool:
    name: 'default'
  steps:
    - bash: |
        ls -la
        echo '123'
