variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: Agent.Diagnostic
    value: true

# resources:
#   containers:
#   - container: my_container
#     image: node:latest
#   - container: nginx
#     image: nginx:latest


# pool: Default

# pool:
#     vmImage: 'ubuntu-latest'
 
# container: my_container
# services:
#   nginx: nginx

# steps:
#   # - script: | 
#   #     curl nginx 
#   - script: |
#       docker ps
#     target: host

#   - script: |
#       cat /etc/hostname
#     target: my_container

#   - script: 
#       cat /etc/hostname
#     target: nginx

# --------------------------------------------------------------------------------------------------

jobs:
  - job: 'Ubuntu'
    pool: "Default"

    steps:
      - task: Bash@3
        inputs:
          targetType: 'inline'
          script: |
            while true
              do
                node file.js
                sleep 120
              done