variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: postgis
    image: ubuntu:20.04
    
jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: ubuntu-latest

  services:
    postgis: postgis

  container:
    image: ubuntu:18.04
  steps:
    - script: docker ps
      target: host
    - script: |
        cat /etc/hostname
      target: 
        container: postgis
# - job: WaitForDocker
#   pool: 
#     vmImage: 'ubuntu-latest'
#   steps:
#     - restoreCache: myKey
#       path: .

#     - saveCache: myKey
#       path: .
#     - checkout: none
#     - bash: |
#         while (! docker stats --no-stream ); do
#           echo "Waiting for Docker to launch..."
#           sleep 1
#         done
# - job: DockerStarted
 
#   dependsOn: WaitForDocker 
#   steps:
#   - script: printenv