name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00'

jobs:
- job: 'ArciveFilesWin2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  steps:
  - template: src\archive-files\templates\jobs-template.yml

- job: 'ArciveFilesHosted2017'
  displayName: Windows2019
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
  - template: src\archive-files\templates\jobs-template.yml

- job: 'ArciveFiles_Ubuntu_1804'
  displayName: Ubuntu_1804
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-18.04'
  steps:
  - template: src\archive-files\templates\jobs-template.yml

- job: 'ArciveFiles_Ubuntu_2004'
  displayName: Ubuntu_2004
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-20.04'
  steps:
  - template: src\archive-files\templates\jobs-template.yml

- job: 'MacOS_Public_Catalina'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-10.15'
  steps:
  - template: src\archive-files\templates\jobs-template.yml

- job: 'MacOS_Public_BigSur'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-11'
  steps:
  - template: src\archive-files\templates\jobs-template.yml
