parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues

jobs:
- job: WaitForDocker
  pool: 
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      git config --global --get-regexp core
      git config --global --get-regexp pack
      
      git config --global core.packedGitLimit 8m
      git config --global core.packedGitWindowSize 8m
      git config --global pack.deltaCacheSize 8m
      git config --global pack.windowMemory 8m

      git config --global --get-regexp core
      git config --global --get-regexp pack
      

  - checkout: self
    fetchTags: true
    env: 
      GIT_TRACE: true
      GIT_TRACE_PACK_ACCESS: true
      GIT_TRACE_PACKET: true
      GIT_TRACE_PERFORMANCE: true
      GIT_TRACE_SETUP: true





