# variables:
#  - name: task
#    value: MSBuildV1

# jobs:

# # All tasks on Windows
# - job: build_all_windows
#   displayName: Build all tasks (Windows)
#   condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
#   pool: win-11-pool
#   timeoutInMinutes: 120
#   steps:
#   - template: ci/build-all-steps.yml
#     parameters:
#       os: Windows_NT

# # All tasks on Linux
# - job: build_all_linux
#   displayName: Build all tasks (Linux)
#   condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
#   pool:  win-11-pool
#   steps:
#   - template: ci/build-all-steps.yml
#     parameters:
#       os: Linux

# # Single task
# - job: buildSingle
#   displayName: Build single task
#   condition: and(succeeded(), variables.task)
#   pool: 
#     vmImage: windows-latest
#   steps:
#   - template: ci/build-single-steps.yml

# # Single task
# - job: buildSingle
#   displayName: Build single task
#   condition: and(succeeded(), variables.test)
#   pool:
#     vmImage: windows-2022
#   steps:
#   # Verify min agent version demands
#   - script: |
#     cd ci
#     cd verifyMinAgentDemands
#     npm install
#     node index.js
#   displayName: Verify all min agent demands are valid


# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# stages:
# - stage: __default
#   jobs:
#   - job: Job
#     pool:  win-11-pool
#     steps:
#     - task: CmdLine@2
#       displayName: 'Run a one-line script'
#       inputs:
#         script: echo Hello, world!
#     - task: CmdLine@2
#       displayName: 'Run a multi-line script'
#       inputs:
#         script: |
#           echo Add other tasks to build, test, and deploy your project.
#           echo See https://aka.ms/yaml
#     - task: DownloadSecureFile@1
#       name: caCertificate
#       displayName: 'Download CA certificate'
#       inputs:
#         secureFile: 'get_pip.py'
#     - task: CmdLine@2
#       displayName: 'Run a multi-line script'
#       inputs:
#         script: |
#           echo $(caCertificate.secureFilePath)
#     - script: |
#         cd ci
#         cd verifyMinAgentDemands
#         npm install
#         node index.js
#       displayName: Verify all min agent demands are valid

stages:
- stage: __default
  jobs:
  - job: TestWindows
    pool: 
      vmImage: windows-2022
    steps:
    - task: Npm@1
      inputs:
        command: install # Required. Command. Default: install
        workingDir: ci/verifyMinAgentDemands # Working folder that contains package.json. 
      displayName: Verify all min agent demands are valid (via npm)
    - script: |
        cd ci
        cd verifyMinAgentDemands
        node index.js
  - job: TestDebian
    pool: 
      vmImage: ubuntu-18.04
    steps:
    - task: Npm@1
      inputs:
        command: install # Required. Command. Default: install
        workingDir: ci/verifyMinAgentDemands # Working folder that contains package.json. 
      displayName: Verify all min agent demands are valid (via npm)
    - script: |
        cd ci
        cd verifyMinAgentDemands
        node index.js
  
