parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues

pool: 
  vmImage: 'ubuntu-latest'
jobs:
- job: job1
  steps:
    - task: AzureKeyVault@1
      inputs:
        azureSubscription: my_azure_sub
        keyVaultName: my_key_vault

    - pwsh: |
        $settingsArgs = "-ENABLEFOOBAR "true" -SECRETAPIKEY $(secret_from_keyvault)"
        echo "##vso[task.setvariable variable=value;isOutput=true;isSecret=true;]$settingsArgs"
        echo "$settingsArgs" # MASKED
      name: task

- job: job2
  dependsOn:
    - job1
  variables:
    slotAppSettings: $[ dependencies.job1.outputs['task.value'] ]
  steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        AppSettings: $(slotAppSettings) # UNMASKED
        # other inputs omitted for brevity

    - task: PowerShell@2
      env:
        MYVAR: $(slotAppSettings)
      inputs:
        script: echo "You can't see the secret here:"; echo $Env:MYVAR # MASKED
