# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"
  - name: AGENT_USE_NODE10
    value: true
  - name: VSTSAGENT_DUMP_JOB_EVENT_LOGS
    value: true
  - name: devCmd
    value: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.com'
  - name: disableToolPath
    value: 'C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\CommonExtensions\Microsoft\VSI\DisableOutOfProcBuild'
jobs:
  - job:
    pool: #'agentvmsspool'
      # name: 'Default'
      vmImage: 'windows-2022'
    steps: 
      - script: ls "C:\Program Files\Microsoft Visual Studio\2022\Enterprise"
      - task: BatchScript@1
        displayName: Enable .vdproj Builds
        inputs:
          filename: '"$(disableToolPath)\DisableOutOfProcBuild.exe"'
          workingFolder: '"$(disableToolPath)"'
      - script: '"$(devCmd)" "$(System.DefaultWorkingDirectory)\LegacyWindowsFormsApp\LegacyWindowsFormsApp.sln" /log "$(Agent.BuildDirectory)\msi_log.xml" /out "$(Agent.BuildDirectory)/out.txt" /Build "Release" /Project "$(System.DefaultWorkingDirectory)\LegacyWindowsFormsApp/LegacyWindowsFormsApp/LegacyWindowsFormsApp.csproj"'
      # - task: BatchScript@1
      #   continueOnError: true
      #   inputs:
      #     filename: 'test.cmd'
      #     arguments: '$(System.DefaultWorkingDirectory) $(Agent.BuildDirectory)'
      - script: |
          ls $(Agent.BuildDirectory)
          cat $(Agent.BuildDirectory)/msi_log.xml
      - script: |
          ls $(Agent.BuildDirectory)
          cat $(Agent.BuildDirectory)/out.txt