variables:
  NODE_OPTIONS: --max_old_space_size=2048

stages:
- stage: __default
  jobs:
  - job: WinTest
    pool: 
      vmImage: windows-2019
    steps:
    - task: UseNode@1
      inputs:
        version: 'v14.17.1'
      displayName: 'Install Node.js v14.17.1'
    - script: | 
        node -v
        npm -v
      displayName: Show npm and node version After
    - task: UseNode@1
      inputs:
        version: 'v18.3.0'
        checkLatest: true
      displayName: 'Install Node.js v18.3.0'
    - script: | 
        node -v
        npm -v
      displayName: Show npm and node version After
    - task: UseNode@1
      inputs:
        version: 'v12.4.0'
        checkLatest: true
        force32bit: true
      displayName: 'Install 32bit Node.js v12.4.0'
    - script: | 
        node -v
        npm -v
      displayName: Show npm and node version After
  - job: UbuntuTest
    pool: 
      vmImage: ubuntu-latest
    steps:
    - task: UseNode@1
      inputs:
        version: 'v14.17.1'
      displayName: 'Install Node.js v14.17.1'
    - script: | 
        node -v
        npm -v
      displayName: Show npm and node version After
    - task: UseNode@1
      inputs:
        version: 'v18.3.0'
        checkLatest: true
      displayName: 'Install Node.js v18.3.0'
    - script: | 
        node -v
        npm -v
      displayName: Show npm and node version After