variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

jobs:
- job: job1
  pool:
      vmImage: 'macOS-11'
  steps:
    - bash: xcode -v 
    - bash: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer"'
      displayName: 'Set Xcode 13.1 as default'
    - bash: xcode -v 
    
- job: job2
  pool:
    vmImage: 'macOS-11'
  steps:
    - bash: xcode -v 
    - bash: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_13.1.app/Contents/Developer"'
      displayName: 'Set Xcode 13.1 as default'
    - bash: xcode -v 
