variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: job1
  pool:
    vmImage: 'macOS-12'
  steps:
    - script: | 
        mkdir testArchieve
        touch testArchieve/testFile.txt
        touch testArchieve/.testFile.txt
        touch testArchieve/testFile2.txt
        touch testArchieve/.testFile2.txt
        mkdir testArchieve/folder
        mkdir testArchieve/.folder
      
    - task: ArchiveFiles@2
      displayName: 'Create tar archive'
      inputs:
        rootFolderOrFile: 'testArchieve'
        archiveType: tar
        archiveFile: 'testArchieve.tar.gz'

    - script: |
        mkdir example
        mv testArchieve.tar.gz example
        cd example
        tar -xf testArchieve.tar.gz
        ls -A testArchieve
    