parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
pool:
  vmImage: 'windows-latest'



steps:
- task: IISWebAppDeploymentOnMachineGroup@0
  inputs:
    WebSiteName: 'test'
    VirtualApplication: 'superApp'
    Package: '$(System.DefaultWorkingDirectory)\_packag\task.zip'
    AdditionalArguments: '-skip:objectName=filePath,absolutePath=web\.\w+\.config|nlog\.\w+\.config'