variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: ubuntu
    image: ubuntu:latest
  - container: postgis
    image: postgis:15-3.3
    ports:
    - 5432
    env:
      POSTGRES_USER: test
      POSTGRES_PASS: test 
      POSTGRES_DBNAME: test 
      ALLOW_IP_RANGE: 0.0.0.0/0

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'ubuntu-latest'

  container: my_container

  steps:
  - script: |
      echo $AGENT_SERVICES_POSTGIS_PORTS_5432
  - script: docker ps
    target: host

  - script: cat /etc/hostname
    target:
        container: postgis
  
  - script: cat /etc/hostname
    target:
      container: ubuntu

# - job: example
#   pool: 'Default'
#   container: my_container

#   steps:
#   - script: docker ps
#     target: host

#   - script: cat /etc/hostname
#     target:
#         container: nginx

#   - script: cat /etc/hostname
#     target:
#       container: my_container