# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool: mac-mini-pool

steps:
- task: StagePreJobTask@0
  inputs:
    samplestring: 'This is a pre job stage'

- task: StageJobTask@0
  inputs:
    samplestring: 'This is a job stage'

- task: StagePostJobTask@0
  inputs:
    samplestring: 'This is a post job stage'

