variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

# resources:
#   containers:
#   - container: my_container
#     image: node:latest
#   - container: nginx
#     image: nginx:latest


# pool: Default

# pool:
#     vmImage: 'ubuntu-latest'
 
# container: my_container
# services:
#   nginx: nginx

# steps:
#   # - script: | 
#   #     curl nginx 
#   - script: |
#       docker ps
#     target: host

#   - script: |
#       cat /etc/hostname
#     target: my_container

#   - script: 
#       cat /etc/hostname
#     target: nginx

# --------------------------------------------------------------------------------------------------

jobs:
  - job: 'Ubuntu'
    pool:
      vmImage: 'ubuntu-latest'

    container: ubuntu:18.04

    steps:
    - task: JavaToolInstaller@0
      inputs:
        versionSpec: '8'
        jdkArchitectureOption: 'x64'
        jdkSourceOption: 'AzureStorage'
        azureResourceManagerEndpoint: 'CIX_Eng (371d9573-3b58-46e5-8489-aac909ffc94c)'
        azureStorageAccountName: 'testjdkloc'
        azureCommonVirtualFile: '5'
        jdkDestinationDirectory: '65'
        cleanDestinationDirectory: true