variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: 'Debian'
  displayName: Debian
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
    # - task: JenkinsQueueJob@1.100.1
    #   displayName: 'Queue Jenkins Job: Parameterized'
    #   inputs:
    #     serverEndpoint: 'ABTT_JenkinsContainer'
    #     jobName: 'BuildCanary_Parameterized'
    #     jobParameters: |
    #       MyBoolean=True
    #       MyString=TestString123
    #   retryCountOnTaskFailure: 3 
    - task: AzureRMWebAppDeployment@4
      inputs:
        appType: webApp
        ConnectedServiceName: ''
        WebAppName: '[NAME]'
        Package: $(PIPELINE.WORKSPACE)/Build/drop/**/*.zip
