variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    value: true

stages:
- stage: 'Win'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      secureSteps: 'download-secure-file-steps-win.yml'
      pool:
        name: 'win-11-pool'
        demands:
          - Agent.Name -equals win-11-ms
  - job: InstallSSHKey_Windows
    displayName: 'Test InstallSSHKey on Windows'
    pool:
      name: 'win-11-pool'
      demands:
        - Agent.Name -equals win-11-ms
    steps:
    - template: templates/test-install-key-win.yml

- stage: 'Debian'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      secureSteps: 'download-secure-file-steps-lin.yml'
      pool:
        name: 'win-11-pool'
        demands:
          - Agent.Name -equals debian-agent
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Hosted Ubuntu 1804'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool:
        name: 'win-11-pool'
        demands:
          - Agent.Name -equals debian-agent

- stage: 'DebianViaContainer'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-container-template.yml
    parameters:
      pool:
        name: 'win-11-pool'
        demands:
          - Agent.Name -equals debian-agent
