variables:
  - name: ndkPath
    value: C:\Android\android-sdk\ndk\23.2.8568313
  - name: androidSdkPath
    value: TEST_SDK_PATH

stages:
  - stage: 'Win2019'
    dependsOn: []
    jobs:
    - job: 'default'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-vs2019.yml
    - job: 'ndk_default'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-ndk-default.yml
  
  - stage: 'Win2022'
    dependsOn: []
    jobs:
    - job: 'default'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2022'
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-vs2019.yml
  
    - job: 'ndk_default'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2022'
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-ndk-default.yml
    
  
  - stage: 'MacOS_Public_Catalina_NDK_default'
    dependsOn: []
    jobs:
    - job: 'ndk_default'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-10.15'
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-ndk-default.yml
  
  - stage: 'MacOS_Public_Catalina'
    dependsOn: []
    jobs:
    - job: 'App1'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-10.15'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK:
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-macOS-app1.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
    - job: 'App2'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-10.15'
      strategy:
        matrix:
          android_11.2_mono_6.12:
            XAMARIN_SYMLINK: 6_12_7
            NETCORE_VERSION: 5.0.202
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-macOS-app2.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          NETCORE_VERSION: $(NETCORE_VERSION)
  
    - job: 'Android_ndk_test_app'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-10.15'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK: ''
            NDK_VERSION: ''
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-ndk.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          NDK_VERSION: $(NDK_VERSION)
  
  - stage: 'MacOS_Public_BigSur'
    dependsOn: []
    jobs:
    - job: 'App1'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-11'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK:
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-macOS-app1.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
    - job: 'App2'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-11'
      strategy:
        matrix:
          android_12.2_mono_6.12:
            XAMARIN_SYMLINK: 6_12_16
            NETCORE_VERSION: 5.0.408
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-macOS-app2.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          NETCORE_VERSION: $(NETCORE_VERSION)
    - job: 'Android_ndk_test_app'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-11'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK: ''
            NDK_VERSION: ''
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-ndk.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          NDK_VERSION: $(NDK_VERSION)
  
  - stage: 'MacOS_Public_Monterey'
    dependsOn: []
    jobs:
    - job: 'App1'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-12'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK:
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-macOS-app1.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
    - job: 'App2'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-12'
      strategy:
        matrix:
          android_12.2_mono_6.12:
            XAMARIN_SYMLINK: 6_12_16
            NETCORE_VERSION: 5.0.408
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-macOS-app2.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          NETCORE_VERSION: $(NETCORE_VERSION)
    - job: 'Android_ndk_test_app'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'macos-12'
      strategy:
        matrix:
          default:
            XAMARIN_SYMLINK: ''
            NDK_VERSION: ''
      steps:
      - template: src/xamarin-android/templates/xamarin-android-test-ndk.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          NDK_VERSION: $(NDK_VERSION)