jobs:

  - job: 'Win2019'
    displayName: Self Hosted Debian
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-18.04'
    steps:
      - task: NodeTool@0
        inputs:
          versionSpec: '10.x' 
      
      - script: echo $LD_LIBRARY_PATH

      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.10.5'
      
      - script: echo $LD_LIBRARY_PATH

      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.5.10'

      - script: echo $LD_LIBRARY_PATH

      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.10.5'