# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: false
  - name: ARGS
    value: "123"
  - name: AGENT_USE_NODE10
    value: true
  - name: VSTSAGENT_DUMP_JOB_EVENT_LOGS
    value: true

jobs:
  - job:
    pool: #'agentvmsspool'
      # name: 'Default'
      vmImage: 'windows-2022'
    steps: 
      - task: CmdLine@2
        continueOnError: true
        inputs:
          script: |
            "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\devenv.exe" "D:\Agent2_GAFVSO\_work\766\s\InsulationFoams\InsulationFoams.sln" /log "$(Agent.BuildDirectory)/SetupIntugentPI/msi_log.xml" /out "$(Agent.BuildDirectory)/SetupIntugentPI/out.txt" /Build "Release" /Project "D:\Agent2_GAFVSO\_work\766\s\SetupIntugentPI\SetupIntugentPI.vdproj"
          failOnStderr: true
      - script: |
          ls $(Agent.BuildDirectory)
          cat $(Agent.BuildDirectory)/msi_log.xml
      - script: |
          ls $(Agent.BuildDirectory)
          cat $(Agent.BuildDirectory)/out.txt
      # - task: AzureRmWebAppDeployment@4
      #   inputs:
      #     ConnectionType: 'AzureRM'
      #     azureSubscription: 'CIX_Eng (371d9573-3b58-46e5-8489-aac909ffc94c)'
      #     # WebAppKind: 'app'
      #     WebAppKind: 'webApp'
      #     WebAppName: 'vbobreshev-test-web-app'
      #     Package: '$(System.DefaultWorkingDirectory)/**/site.zip'
      #     UseWebDeploy: true
      #     # AdditionalArguments: '-skip:objectName=filePath,absolutePath="^.*\.config$" -skip:objectName=filePath,absolutePath="favicon.ico" -skip:objectName=filePath,absolutePath="appsettings.json" -skip:objectName=dirPath,absolutePath=${{ parameters.skipFolder }}'
      #     AdditionalArguments: -skip:objectName=filePath,absolutePath="^.*\.config$" -skip:objectName=filePath -skip:objectName=filePath,absolutePath="favicon.ico" -skip:objectName=filePath,absolutePath="appsettings.json" -skip:objectName=dirPath,absolutePath="^.*Resources(?!CL|Generic|\|$).*$" -skip:objectName=dirPath,absolutePath=^.*Resources(?!CL|"|Generic|\|$).*$ -skip:objectName=dirPath,absolutePath="^.*Resources(?!| \\"CL|Generic|\|$).*$" -skip:objectName=dirPath,absolutePath='^.*Resources(?!CL|"|Generic|\|$).*$' -skip:asd
      # - task: NodeTool@0
      #   displayName: 'Use Node 18.16.1'
      #   inputs:
      #     versionSpec: 18.16.1
      #     checkLatest: true
      # - script: node -v
      #   displayName: 'node version'
      
      # - task: UseNode@1
      #   displayName: 'Use Node 17'
      #   inputs:
      #     version: 17.x
      #     checkLatest: true