name: '##%C0%BCscript%C0%BEalert(1)%C0%BC/script%C0%BE##1'

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'
  - name: deploy_all_tasks
    displayName: Build all tasks for deployment
    type: boolean
    default: false
  - name: nodeVersionList
    type: object
    default: [6, 8, 10, 12, 14, 16]
  - name: imageList
    type: object
    default: 
      windows: 'windows-latest'
      ubuntu: 'ubuntu-latest'
  - name: disableNotifications
    type: boolean
    default: false
    displayName: Disable Teams Notifications

variables:
  - name: System.Debug
    value: false
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default 
  vmImage: 'ubuntu-latest'

steps:
  - powershell: mkdir testssh
  - powershell: |
      cd testssh
      $rootDir = Get-Location
      $baseFile = $rootDir.Path + "base.txt"
      $desiredFileSize = 2*1KB
      $fileCount = 2000
      "start" | Out-File -Filepath $baseFile
      While ($(Get-ChildItem -path $baseFile).Length -lt $desiredFileSize)
      {
          $(Get-ChildItem -path $baseFile).Length | Out-File $baseFile -APPEND
      }
      for($i=1;$i -lt $fileCount;$i++)
      {
          Copy-Item $baseFile "File$i.txt"
      }
  - task: CopyFilesOverSSH@0
    inputs:
      sshEndpoint: 'test_ssh'
      sourceFolder: 'testssh'
      contents: '**'
      targetFolder: 'test'
      readyTimeout: '20000'