name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00'

stages:
- stage: 'ArchiveFilesWin2022'
  pool:
    name: 'Default'
  jobs:
    - job: 'TestInCorrect'
      displayName: 'Test incorrect checkout'
      steps:
        - checkout: self
          path: s/
        - checkout: git://playground/playground
          path: s/roles/logstash
          clean: false