
parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: ['3','4']
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: ['1', '2']
  - name: allModules
    type: string
    default: ''
    values:
      - 
    ${{each item in parameters}}:
      ${{if contains(item.name, '_module')}}: 
      - ${{item.name}}

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues
    ${{each item in parameters}}:
      ${{if contains(item.name, '_module')}}: 
      value:  ${{ join(';',item.name) }}
       # here I want to concatenate all the parameters names that have name _module but this statement is throwing an error 

jobs:
- job: job1
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - script: echo $(allValues)

