variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: job1
  steps:
    - pwsh: |
        $settingsArgs = "-ENABLEFOOBAR "true" -SECRETAPIKEY $(secret_from_keyvault)"
        echo "##vso[task.setvariable variable=value;isOutput=true;isSecret=true;]$settingsArgs"
        echo "$settingsArgs"
      name: task

- deployment: job2
  dependsOn:
    - job1
  variables:
    slotAppSettings: $[ dependencies.job1.outputs['task.value'] ]
  steps:
    - task: AzureRmWebAppDeployment@4
      inputs:
        AppSettings: $(slotAppSettings)
        # other inputs omitted for brevity
    - pwsh: echo "MASKED: $env:myvar"
      env:
        myvar: $(slotAppSettings)