variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

pool:
  name: 'Azure Pipelines'
  vmImage: 'ubuntu-latest'
steps:
  - task: CmdLine@2
    inputs:
      script: |
        wget $(secretVariable)
        wget http://deb.debian.org/debian-security/$(secredVarWithPartUrl)