variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

resources:
  containers:
  - container: my_container
    image: node:latest
  - container: nginx
    image: nginx:latest


# pool: Default

pool:
    vmImage: 'ubuntu-latest'
 
container: nginx
services:
  my_container: my_container

steps:
  # - script: | 
  #     curl nginx 
  - script: |
      docker ps
    target: host

  - script: |
      cat /etc/hostname
    target: my_container

  - script: 
      cat /etc/hostname
    target: nginx