# variables:
#  - name: task
#    value: MSBuildV1

# jobs:

# # All tasks on Windows
# - job: build_all_windows
#   displayName: Build all tasks (Windows)
#   condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
#   pool: win-11-pool
#   timeoutInMinutes: 120
#   steps:
#   - template: ci/build-all-steps.yml
#     parameters:
#       os: Windows_NT

# # All tasks on Linux
# - job: build_all_linux
#   displayName: Build all tasks (Linux)
#   condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
#   pool:  win-11-pool
#   steps:
#   - template: ci/build-all-steps.yml
#     parameters:
#       os: Linux

# # Single task
# - job: buildSingle
#   displayName: Build single task
#   condition: and(succeeded(), variables.task)
#   pool: 
#     vmImage: windows-latest
#   steps:
#   - template: ci/build-single-steps.yml

# # Single task
# - job: buildSingle
#   displayName: Build single task
#   condition: and(succeeded(), variables.test)
#   pool:
#     vmImage: windows-2022
#   steps:
#   # Verify min agent version demands
#   - script: |
#     cd ci
#     cd verifyMinAgentDemands
#     npm install
#     node index.js
#   displayName: Verify all min agent demands are valid


# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  NODE_OPTIONS: --max_old_space_size=125

stages:
- stage: __default
  jobs:
  - job: Job
    pool:  win-11-pool
    steps:
    - task: DownloadSecureFile@1
      name: caCertificate
      displayName: 'Download CA certificate'
      inputs:
        secureFile: 'test.js'
    - task: DownloadSecureFile@1
      name: BigFileTest
      displayName: 'Download Big File'
      inputs:
        secureFile: '1.txt'
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          node $(caCertificate.secureFilePath)
    - task: CmdLine@2
      displayName: 'Check NodeJs HeapSize'
      inputs:
        script: |
          node -e "
            const v8 = require('v8');
            const totalHeapSize = v8.getHeapStatistics().total_available_size;
            const totalHeapSizeGb = (totalHeapSize / 1024 / 1024 / 1024).toFixed(2);
            console.log('totalHeapSizeGb: ', totalHeapSizeGb)
          "
