# resources:


#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
- name: solutionTarget
  type: string
  default: 'someSolutionTarget'
- name: msBuildArguments
  type: string
  default: ''
- name: binSourcePath
  type: string
  default: ''

variables:
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: agent.diagnostic
    value: true
  - name: sourceDir
    value: $(Build.SourcesDirectory)

jobs:
- job: 'Example'
  pool:
    # name: 'Default'
    vmImage: 'ubuntu-latest'
  steps:
    - task: CondaEnvironment@0
      inputs:
        environmentName: myEnvironment
        updateConda: false # boolean. Update to the latest Conda. Default: true.
      # Advanced
        #createOptions: # string. Environment creation options. 
        #cleanEnvironment: false # boolean. Clean the environment. Default: false.

    - bash: |
        cd src/conda/src
        source activate myEnvironment
        pip install pytest pytest-azurepipelines
        pytest
      displayName: pytest
      retryCountOnTaskFailure: 3
