variables:
  - name: ndkPath
    value: C:\Android\android-sdk\ndk\23.2.8568313
  - name: androidSdkPath
    value: TEST_SDK_PATH

jobs:
  - job: 'Ubuntu'
    displayName: Ubuntu Latest
    pool:
      name: 'default'
      vmImage: debian
    steps:
      - template: src/curl-uploader/curl-uploader-steps.yml
        parameters:
          sshEndpoint: 'root@68.183.10.251'
          ftpEndpoint: 'root@68.183.10.251'