variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources 
    value: true
  - name: passphrase
    value: 4eba4y
  - name: agentName
    value: mac-mini-arm64
  - name: poolName
    value: win-11-pool

stages:
- stage: 'Win'
  dependsOn: []
  jobs:
  - job: UseNodeV1
    displayName: 'Test UseNodeV1 Taskw'
    pool:
      name: $(poolName)
      demands:
        - Agent.Name -equals $(agentName)
    strategy:
      matrix:
        Node10:
          node.version: '10.x'
        Node12:
          node.version: '12.x'
        Node14:
          node.version: '14.x'
        Node16:
          node.version: '16.x'
    steps:
    - template: src/node/templates/node-toolcache-steps.yml
      parameters:
        nodeVersion: $(node.version)

