# name: $(SourceBranchName)_$(Date:yyyyMMdd)

# parameters:
#   - name: applications_module
#     displayName: Applications
#     type: boolean
#     default: 'false'
#     values: []
#   - name: management
#     displayName: Management
#     type: boolean
#     default: 'false'
#     values: []
#   - name: It
#     displayName: IT_module
#     type: boolean
#     default: 'false'
#     values: []

variables:
#   - name: System.Debug
#     value: true
#   - name: build.clean
#     value: all
#   - name: agent.clean.buildDirectory
#     value: all
#   - name: buildPlatform
#     value: 'Any CPU'
#   - name: buildConfiguration
#     value: 'UNIT_TEST'
#   - name: AGENT_USE_NODE10
#     value: true
  - name: BuildNameTest
    value: 'ubuntu-build-number-1' 
      
# jobs:
# - job: BuildUbubntu
pool:
  name: Default
  # name: Azure Pipelines
  # vmImage: ubuntu-latest

steps:
- checkout: none
- script: |
    echo "##vso[build.addbuildtag]BuildName=e00f8cf4-8b30-43ff-97b5-eb3aae673193"
    echo "##vso[build.addbuildtag]Tag_UnitTestPassed"
    echo "##vso[build.addbuildtag]8.22.12.09.3519204.FMBase_Main.inc"
    echo "##vso[build.addbuildtag]Res=asd"
    ECHO ##vso[build.updatebuildnumber]$(BuildNameTest)
  displayName: 'Update Build Number 1'
- bash: |
    sleep 10s
  displayName: 'Sleep'
- bash: |
    echo "##vso[task.setvariable variable=ProjectBuildNumber;]ubuntu-build-number-2"
  displayName: 'Update Build Number 2'

# - job: BuildMacOS
#   pool:
#     name: Azure Pipelines
#     vmImage: macos-latest

#   steps:
#   - bash: |
#       echo "##vso[build.updatebuildnumber]macos-build-number-1"
#     displayName: 'Update Build Number 1'
#   - bash: |
#       sleep 100s
#     displayName: 'Sleep'
#   - bash: |
#       echo "##vso[build.updatebuildnumber]macos-build-number-2"
#     displayName: 'Update Build Number 2'


# - job: BuildWindows
#   pool:
#     name: Azure Pipelines
#     vmImage: windows-latest

#   steps:
#   - bash: |
#       echo "##vso[build.updatebuildnumber]windows-build-number-1"
#     displayName: 'Update Build Number 1'
#   - bash: |
#       ping 127.0.0.1 -n 100 > nul
#     displayName: 'Sleep'
#   - bash: |
#       echo "##vso[build.updatebuildnumber]windows-build-number-2"
#     displayName: 'Update Build Number 2'

# - job: BuildUbubntuContainer
#   container: ubuntu:18.04
#   pool:
#     name: Azure Pipelines
#     vmImage: ubuntu-latest

#   steps:
#   - bash: |
#       echo "##vso[build.updatebuildnumber]ubuntu-container-build-number-1"
#     displayName: 'Update Build Number 1'
#   - bash: |
#       sleep 100s
#     displayName: 'Sleep'
#   - bash: |
#       echo "##vso[build.updatebuildnumber]ubuntu-container-build-number-2"
#     displayName: 'Update Build Number 2'

# - job: BuildWindowsContainer
#   container: ubuntu:18.04
#   pool:
#     name: Azure Pipelines
#     vmImage: windows-latest

#   steps:
#   - bash: |
#       echo "##vso[build.updatebuildnumber]windows-container-build-number-1"
#     displayName: 'Update Build Number 1'
#   - bash: |
#       sleep 100s
#     displayName: 'Sleep'
#   - bash: |
#       echo "##vso[build.updatebuildnumber]windows-container-build-number-2"
#     displayName: 'Update Build Number 2'