parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  - name: AGENT_TOOLSDIRECTORY
    value: test1
pool: Default
  #vmImage: ubuntu-latest

# container:
#   image: alpine:latest
#   endpoint: private_dockerhub_connection

jobs:
- job: 
  variables:
    - name: AGENT_TOOLSDIRECTORY
      value: test2
  steps:
    - powershell: echo "$env:AGENT_TOOLSDIRECTORY"
      env: 
        AGENT_TOOLSDIRECTORY: test3