variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: job1
  pool:
    vmImage: 'windows-latest'
  steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: 'src/npm/.npmrc'
    - pwsh: |
        echo "##vso[task.setvariable variable=value;isOutput=true;]testvarbetweenjobs"
      name: task
    - pwsh: |
        cd src/npm;
        npm install --save-dev

- job: job2
  pool:
    vmImage: 'windows-latest'
  dependsOn:
    - job1
  variables:
    slotAppSettings: $[ dependencies.job1.outputs['task.value'] ]
  steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: 'src/npm/.npmrc'
    - task: Npm@1
      inputs:
        command: install
        workingDir: src/npm

- job: job3
  pool:
    vmImage: 'windows-latest'
  dependsOn:
    - job2
  steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: 'src/npm/.npmrc'
    - task: Npm@0
      inputs:
        command: install
        cwd: src/npm