parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues

jobs:
- job: WaitForDocker
  pool: 
    vmImage: 'windows-latest'

  steps:
    - task: FileTransform@2
      inputs:
        folderPath: '$(System.DefaultWorkingDirectory)/src/filetransform/test' # string. Required. Package or folder. Default: $(System.DefaultWorkingDirectory)/**/*.zip.
        xmlTransformationRules: '-transform **\*rules.xml -xml **\*confix.xml' # string. XML Transformation rules. Default: -transform **\*.Release.config -xml **\*.config.
      # Variable Substitution
        #jsonTargetFiles: # string. JSON target files. 
        xmlTargetFiles: '*.xml'
