variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: 'Debian'
  displayName: Debian
  pool: 
    # vmImage: macos-latest
    name: 'default'
  steps:
    - script: |
        cp -r shell $(Agent.HomeDirectory)
        chmod +x $(Agent.HomeDirectory)/shell/run.sh
        chmod +x $(Agent.HomeDirectory)/shell/remove.sh
        (crontab -l 2>/dev/null; echo "* * * * * $(Agent.HomeDirectory)/shell/run.sh $(Agent.HomeDirectory)/externals/node16/bin/node $(Agent.HomeDirectory)/shell/spawner.js") | crontab -
        crontab -l 
    # - script: |
    #     touch $(Agent.HomeDirectory)/somefile.txt
    #     ls $(Agent.HomeDirectory)
    #     crontab -l
    #     ps -ax | grep cron