jobs:
  - job: 'Win2022s'
    displayName: Windows VS2022
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    steps:
      - template: src/msbuild/msbuild-steps.yml
        parameters:
          solutionPath: '$(build.sourcesdirectory)/src/msbuild/projects/SimpleConsoleAppCore3/SimpleConsoleAppCore3.sln'
      - template: src/msbuild/msbuild-steps.yml
        parameters:
          solutionPath: '$(build.sourcesdirectory)/src/msbuild/projects/SimpleConsoleAppCore2/TestConsoleApp.sln'