parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: false
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: ubuntu-latest

# container:
#   image: alpine:latest
#   endpoint: private_dockerhub_connection

jobs:
- job: 
  steps:
    - task: Npm@1
      inputs:
        command: 'custom'
        customCommand: 'clean-install'
      displayName: "\U0001F4E6 Install npm packages"