parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'
  - name: deploy_all_tasks
    displayName: Build all tasks for deployment
    type: boolean
    default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: 'ubuntu-latest'

stages:
- stage: first_stage
  jobs:
  - job: first_job
    pool: #Default
       vmImage: macos-latest
    steps:
      - script: brew install openssl
      - script: openssl pkcs12 --help 