variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: ubuntucontainer
    image: ubuntu:latest
    options: --hostname ubuntu-test --name ubuntu-test
  - container: nginx
    image: nginx
    options: --hostname nginx-test --name nginx-test
    ports:
    - 8080:80
    env:
      NGINX_PORT: 80

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'ubuntu-latest'
  container: ubuntucontainer

  steps:
  # - script: 
  #     docker-machine ip default

  - script: |
      docker ps
      IP=`docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx-test`
      echo "##vso[task.setvariable variable=nginx-test-ip;]$IP"
    target: host

  - script: 
      cat /etc/hostname
    target:
        container: nginx
  
  # - script: |
  #     apt get install -y nmap
  #     echo $(agent.containernetwork)
  #     echo $(nginx-test-ip)
  #     nmap  -v -A $(nginx-test-ip)
  #     nmap  -v -A localhost
  #   target: host

  - script: |
      apt=get install curl
      echo $(nginx-test-ip)
      curl $(nginx-test-ip):8080

# - job: example
#   pool: 'Default'
#   container: my_container

#   steps:
#   - script: docker ps
#     target: host

#   - script: cat /etc/hostname
#     target:
#         container: nginx

#   - script: cat /etc/hostname
#     target:
#       container: my_container