variables:
  - name: System.Debug
    value: false
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 

pool: Default 
  #vmImage: windows-latest

steps:
  - task: DotNetCoreCLI@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'

  - task: UsePythonVersion@0
    inputs:
      versionSpec: "^3.13.0-0"
      architecture: "x64"
      allowUnstable: true
    displayName: "Use Python 3.13.0-rc.2 x64"