variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
  - job: 'Hosted_Ubuntu_2004'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    steps:
      - template: src/copy-files-over-ssh/copy-files-over-ssh-steps.yml
        parameters:
          sshEndpoint: 'ABTT_Ubuntu_SSH_container'
  
  - job: 'Hosted_Ubuntu_2204'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-22.04'
    steps:
      - template: src/copy-files-over-ssh/copy-files-over-ssh-steps.yml
        parameters:
          sshEndpoint: 'ABTT_Ubuntu_SSH_container'
