stages:
- stage: 'Win'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'

- stage: 'Debian'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2022'

# - stage: 'Debian via container'
#   dependsOn: []
#   jobs:
#   - template: src/agentTest/agent-test-installer-tasks-container-template.yml
#     parameters:
#       pool: 
#         name: 'Azure Pipelines'
#         vmImage: 'ubuntu-18.04'

