variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: alpine
    image: ellerbrock/alpine-bash-curl-ssl
  - container: nginx
    image: nginx
    ports:
    - 8080:80
    env:
      NGINX_PORT: 80

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      docker network ls
      docker ps
      curl localhost:8080
    target: host

  - script: cat /etc/hostname
    target:
        container: nginx
  
  - script: | 
      cat /etc/hostname
      curl localhost:8080
    target:
      container: alpine

# - job: example
#   pool: 'Default'
#   container: my_container

#   steps:
#   - script: docker ps
#     target: host

#   - script: cat /etc/hostname
#     target:
#         container: nginx

#   - script: cat /etc/hostname
#     target:
#       container: my_container