parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: windows-latest
 
steps:
  # - task: DotNetCoreCLI@2
  #   inputs:
  #     command: 'restore'
  #     projects: 'src/nuget/nugetv2/ExternalDependency/**/*.sln'
  #     feedsToUse: 'select'
  #     vstsFeed: '917e7969-c65a-47e6-a8e8-22958014172d'

  - task: DotNetCoreCLI@2
    displayName: 'NuGet restore |NuGet.config external feed|'
    continueOnError: true
    inputs:
      projects: 'src/nuget/nugetv2/ExternalDependency/**/*.sln'
      feedsToUse: config
      nugetConfigPath: src/nuget/nugetv2/ExternalDependency/nuget.config
      externalFeedCredentials: 'ABTTestOrg@Private'
      noCache: true