variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

jobs:
- job: WaitForDocker
  pool: 'Default'
  steps:
    - checkout: none
    - bash: |
        while (! docker stats --no-stream ); do
          echo "Waiting for Docker to launch..."
          sleep 1
        done
- job: DockerStarted
  pool: 'Default'
  container: ubuntu:18.04
  dependsOn: WaitForDocker 
  steps:
  - script: printenv