variables:
  NODE_OPTIONS: --max_old_space_size=2048

stages:
- stage: __default
  jobs:
  - job: 'Ubuntu_1804'
    displayName: Test DownloadSecureFileV1 on Ubuntu 1804
    pool: 
      vmImage: ubuntu-18.04
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'Ubuntu_2004'
    displayName: Test DownloadSecureFileV1 on Ubuntu 2004
    pool: 
      vmImage: ubuntu-20.04
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'Ubuntu_2204'
    displayName: Test DownloadSecureFileV1 on Ubuntu 2204
    pool: 
      vmImage: ubuntu-22.04
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'Win2019'
    displayName: Test DownloadSecureFileV1 on Windows 2019
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'Win2022'
    displayName: Test DownloadSecureFileV1 on Windows 2022
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'MacOS_Public_Catalina'
    displayName: Test DownloadSecureFileV1 on MacOS Catalina
    pool:
      vmImage: 'macos-10.15'
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'MacOS_Public_BigSur'
    displayName: Test DownloadSecureFileV1 on MacOS Big Sur
    pool:
      vmImage: 'macos-11'
    steps:
    - template: templates/download-secure-file-steps.yml
  
  - job: 'MacOS_Public_Monterey'
    displayName: Test DownloadSecureFileV1 on MacOS Monterey
    pool:
      vmImage: 'macos-12'
    steps:
    - template: templates/download-secure-file-steps.yml