parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: false
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: ubuntu-latest

# container:
#   image: alpine:latest
#   endpoint: private_dockerhub_connection

jobs:
- job: 
  timeoutInMinutes: 10
  steps:
    - powershell: |
        cd sample-net
        dotnet build
        ls 
        ls bin
        ls bin/Debug
        sudo chmod +x bin/Debug/net6.0/sample-net
        ./bin/Debug/net6.0/sample-net