# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
parameters:
  - name: branchOptions
    displayName: Source branch options
    type: object
    default:
      - refs/heads/main
      - refs/heads/test

# trigger:
  # enabled: false
stages:
- stage: __default
  jobs:
  - job: Job
    # pool: 'mac-mini-pool'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - ${{ each value in parameters.branchOptions }}:
      - task: NodeTool@0
        displayName: Set node version to 12.x
        inputs:
          versionSpec: '12.x'
      - task: Npm@1
        displayName: 'Install deps'
        inputs:
          command: 'ci'
      - task: CmdLine@2
        displayName: 'Run clean-up'
        inputs:
          script: |
            rm -rf ./node_modules    