parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: false
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: Default
  # vmImage: windows-latest
 
steps:
- task: AzurePowerShell@5
  continueOnError: true
  inputs:
    azureSubscription: 'Build_Eng(3f56da7f-5953-4018-8ca8-e20dbfa0a7e2)'
    ScriptType: 'InlineScript'
    Inline: 'echo "123"'
    azurePowerShellVersion: 'LatestVersion'
    FailOnStandardError: true
    pwsh: true
- task: AzurePowerShell@5
  continueOnError: true
  inputs:
    azureSubscription: 'Build_Eng(3f56da7f-5953-4018-8ca8-e20dbfa0a7e2)'
    ScriptType: 'InlineScript'
    Inline: 'echo "123"'
    azurePowerShellVersion: 'LatestVersion'
    FailOnStandardError: true
    
- task: AzureCloudPowerShellDeployment@1
  inputs:
    azureClassicSubscription: 'Build_Eng(3f56da7f-5953-4018-8ca8-e20dbfa0a7e2)' 
    EnableAdvancedStorageOptions: true
    ARMConnectedServiceName: 'Build_Eng(3f56da7f-5953-4018-8ca8-e20dbfa0a7e2)'
    ARMStorageAccount: 'iismayilov'
    ServiceName: 'test'
    ServiceLocation: 'test'
    CsPkg: 'test'
    CsCfg: 'test'
    slotName: 'Dev'
    AllowUpgrade: false
