variables:
  NODE_OPTIONS: --max_old_space_size=2048

stages:
- stage: __default
  pool: win-11-pool
  jobs:
  - job: 'DebianWSL'
    displayName: Test agent Kirill Task 3362
    container: debian:latest
    steps:
      - script: ls -la