variables:
 - name: task
   value: MSBuildV1

jobs:

# All tasks on Windows
- job: build_all_windows
  displayName: Build all tasks (Windows)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
  pool: win-11-pool
  timeoutInMinutes: 120
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Windows_NT

# All tasks on Linux
- job: build_all_linux
  displayName: Build all tasks (Linux)
  condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
  pool:  win-11-pool
  steps:
  - template: ci/build-all-steps.yml
    parameters:
      os: Linux

# Single task
- job: buildSingle
  displayName: Build single task
  condition: and(succeeded(), variables.task)
  pool: win-11-pool
  steps:
  - template: ci/build-single-steps.yml