variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: 'Debian'
  displayName: Debian
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
    - task: Synapse workspace deployment@2
      inputs:
        operation: 'deploy'
        TargetWorkspaceName: 
        DeleteArtifactsNotInTemplate: false
        DeployManagedPrivateEndpoints: false
        FailOnMissingOverrides: false
        Environment: 'prod'
        npmpackage: 'prod'
    # - task: AzureRMWebAppDeployment@4.1.10
    #   inputs:
    #     appType: webApp
    #     ConnectedServiceName: ''
    #     WebAppName: '[NAME]'
    #     Package: $(PIPELINE.WORKSPACE)/Build/drop/**/*.zip
