variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 

pool: Default 
  # vmImage: windows-latest

steps:
  # - task: NodeTool@0
  #   displayName: Use Node ^18.16.1
  #   inputs:
  #     versionSpec: '^18.16.1'
  # - task: Npm@1
  #   displayName: Install packages
  #   inputs:
  #     command: 'custom'
  #     workingDir: './react-test'
  #     customCommand: 'install --legacy-peer-deps'
  # - task: Bash@3
  #   displayName: 'Bash@3: Run pipeline script'
  #   continueOnError: true
  #   inputs:
  #       targetType: 'inline'
  #       script: npm run itest:ci
  #       workingDirectory: './react-test'
  - pwsh: |
      az version
      az cloud set -n AzureCloud
      az login --service-principal -u "eee80ba7-06ed-423d-911f-bf9ca5cb8ad2" --tenant "771d663d-da6c-44bd-bc0a-e9a46bc4bfb6" --allow-no-subscriptions --federated-token "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiIsIng1dCI6IjdSd2F5dmlYRHFoZnN6MTZSNmxPbXNXWWxTQSIsImtpZCI6IkVEMUMxQUNBRjg5NzBFQTg1RkIzM0Q3QTQ3QTk0RTlBQzU5ODk1MjAifQ.eyJqdGkiOiIxMTYxMjg3Ny02MTIyLTRlOWEtYmUyNS04NjM1ZjdhMWM5NzQiLCJzdWIiOiJzYzovL3YtYm9icmVzaGV2ZC9wbGF5Z3JvdW5kL0F6dXJlRGV2T3BzX3Rlc3QiLCJhdWQiOiJhcGk6Ly9BenVyZUFEVG9rZW5FeGNoYW5nZSIsImlzcyI6Imh0dHBzOi8vdnN0b2tlbi5kZXYuYXp1cmUuY29tLzhlODVmZmRiLWI4N2QtNDMxOS1hODY3LTI1N2Y2ZjU3NzU1NiIsIm5iZiI6MTcyNDc1NzkxOCwiZXhwIjoxNzI0NzU5MTE3LCJpYXQiOjE3MjQ3NTg1MTh9.CElTcyZxV63d3flOWZL7A9vLXSZ_ivF4JZbQDcyENMyIzjH5uA1ptbVwxrt0tbWrAVe1B16ysBQhHhEicQcvvY2TNss6J1jh93qLkmqI1I_S8pgohq7-RLnJo1Eys02FEsQ14rYma_xJvgnVjOcgZtQnsIXw7IBWF9fiZfNplaWuL1q8boeIEwGIw1RhykO8ULc2z2KmDUD6dACfC5vbwKwkVNs2LVZgsNmKOCsGyp-QHeS0PLTVgqeO8G77P2eLoFUtlNbmrKsPQUgjWVKwUgs_N89K7SN-HuyyQKbjf8su4fbI-wiW9AOYTR6iy7if0bDC-YQZPb_fl0uAdCiZsQ"
      az account set --subscription b3d51cea-81f7-426f-90bf-950adeec4e3a
      az keyvault create --location westus2 --name TestKeyVault --resource-group edergachev-agent-and-tasks --debug

  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureDevOps_test'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: az keyvault create --location westus2 --name TestKeyVault --resource-group edergachev-agent-and-tasks --debug