variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    value: true

stages:
- stage: 'Win2017'
  dependsOn: []
  jobs:
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Hosted VS2017'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool:
        name: 'Azure Pipelines'
        vmImage: 'vs2017-win2016'

- stage: 'Win2019'
  dependsOn: []
  jobs:
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Hosted Windows 2019 with VS2019'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'

- stage: 'Win2022'
  condition: and(succeeded(),  contains(variables.targetPools, 'Windows Server 2022'))
  dependsOn: []
  jobs:
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Windows Server 2022'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2022'

- stage: 'ubuntu1804'
  dependsOn: []
  jobs:
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Hosted Ubuntu 1804'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool: 
        name: 'Azure Pipelines'
        vmImage: 'ubuntu-1804'

- ${{ if eq(variables.enableAzureResourcesDependentTests, true) }}:
  - stage: 'MacOs'
    dependsOn: []
    jobs:
    - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-macos.yml
      parameters:
        targetPools: 'Hosted macOS Catalina'
        pool:
          name: 'Azure Pipelines'
          vmImage: 'macos-10.15'
