# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"
  - name: AGENT_USE_NODE10
    value: true
  - name: VSTSAGENT_DUMP_JOB_EVENT_LOGS
    value: true

jobs:
  - job:
    pool: #'agentvmsspool'
      # name: 'Default'
      vmImage: 'windows-2019'
    steps: 
      - task: BatchScript@1
        inputs:
          filename: 'test.cmd'
          arguments: '$(System.DefaultWorkingDirectory) $(Agent.BuildDirectory)'
      - script: |
          ls $(Agent.BuildDirectory)
          cat $(Agent.BuildDirectory)/msi_log.xml
      - script: |
          ls $(Agent.BuildDirectory)
          cat $(Agent.BuildDirectory)/out.txt