variables:
  NODE_OPTIONS: --max_old_space_size=2048

stages:
- stage: __default
  pool: win-11-pool
  jobs:
  - job: 'DebianWSL'
    displayName: Show group and id inside WSL
    steps:
      - script: echo UID:$(id -u), GUID:$(id -g)
  - job: 'DebianContiner'
    displayName: Show group and id inside container
    container: debian:latest
    steps:
      - script: echo UID:$(id -u), GUID:$(id -g)
  - job: 'TaskTestViaContainer'
    displayName: Test some tasks inside container
    container: debian:latest
    steps:
      - script: echo UID:$(id -u), GUID:$(id -g)
      - script: |
          apt-get update
          apt-get install ssh
          apt-get install git
      - template: templates/download-secure-file-steps.yml
      - template: templates/test-install-key.yml
      - task: DownloadSecureFile@1
        name: caCertificate
        displayName: 'Download CA certificate'
        inputs:
          secureFile: 'test.js'
      - task: DownloadSecureFile@1
        name: BigFileTest
        displayName: 'Download Big File'
        inputs:
          secureFile: '1.txt'
      - task: CmdLine@2
        displayName: 'Run a one-line script'
        inputs:
          script: echo Hello, world!
      - task: CmdLine@2
        displayName: 'Run a multi-line script'
        inputs:
          script: |
            echo Add other tasks to build, test, and deploy your project.
            echo See https://aka.ms/yaml
      - script: echo null > test.txt
        displayName: 'Creating file'
      - task: CopyFiles@2
        inputs:
          Contents: test.txt
          TargetFolder: 'testFolder'
        displayName: 'Try to run commund under node10'
      - script: dir
      - task: NodeTool@0
        inputs:
          versionSpec: 'v14.17.1'
        displayName: 'Install Node.js v14.17.1'
      - script: 'npm -v'
        displayName: Show npm version