variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: certificateFileName
    value: CanaryTestCertificateCommonName.p12
  - name: certificatePassword
    value: 4eba4y
  - name: keychainPassword
    value: keychainPassword

stages:
- stage: 'MacOS_Public_Catalina'
  dependsOn: []
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-10.15'
  jobs:
  - template: src/install-apple-certificate/templates/install-apple-certificate-steps.yml

- stage: 'MacOS_Public_BigSur'
  dependsOn: []
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-11'
  jobs:
  - template: src/install-apple-certificate/templates/install-apple-certificate-steps.yml

- stage: 'MacOS_Public_Monterey'
  dependsOn: []
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-12'
  jobs:
  - template: src/install-apple-certificate/templates/install-apple-certificate-steps.yml