jobs:
  - job: 'Win2022s'
    displayName: Windows VS2022
    pool:
      vmImage: windows-2022
    steps:
      - powershell: echo $env:NDK_ROOT
      - task: PowerShell@2
        env:
          NDK_ROOT: 'TEST_NDK_ROOT'
        inputs:
          targetType: 'inline'
          script: echo $env:NDK_ROOT
      - powershell: echo $env:NDK_ROOT