parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: windows-latest

# container:
#   image: alpine:latest
#   endpoint: private_dockerhub_connection

jobs:
- job: 
  steps:
    - pwsh: |
        $mpath = $env:SystemDrive + "\Modules"
        Remove-Item -Recurse -Force $mpath
    - task: AzurePowerShell@5
      inputs:
        azureSubscription: 'AzureDevOps_test'
        ScriptType: 'InlineScript'
        Inline: 'echo "123"'
        preferredAzurePowerShellVersion: 'LatestVersion'
        pwsh: true