variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
  - job: 'Ubuntu1804'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-18.04'
    steps:
    - template: src/cmdLine/templates/basic-execution.yml
    - template: src/cmdLine/templates/ubuntu-specific-case.yml
  
  - job: 'Ubuntu2004'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    steps:
    - template: src/cmdLine/templates/basic-execution.yml
    - template: src/cmdLine/templates/ubuntu-specific-case.yml
  
  - job: 'Ubuntu2204'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-22.04'
    steps:
    - template: src/cmdLine/templates/basic-execution.yml
    - template: src/cmdLine/templates/ubuntu-specific-case.yml
  
  - job: 'Win2019'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - template: src/cmdLine/templates/basic-execution.yml
  
  - job: 'Win2022'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    steps:
    - template: src/cmdLine/templates/basic-execution.yml
