parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues

stages:
- stage: 'Ubuntu_2004'
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)

- stage: 'Ubuntu_2204'
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-22.04'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)

- stage: 'Win2019'
  dependsOn: []
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)

- stage: 'Win2022'
  dependsOn: []
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)

- stage: 'MacOS_Public_Catalina'
  dependsOn: []
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-10.15'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)

- stage: 'MacOS_Public_BigSur'
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted macOS BigSur'))
  dependsOn: []
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-11'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)

- stage: 'MacOS_Public_Monterey'
  jobs:
  - job: 'HelmInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-12'
    strategy:
      matrix:
        Helm3.10.2:
          helm.version: '3.10.2'
        Helm3.5.4:
          helm.version: '3.5.4'
        Helm2.16.7:
          helm.version: '2.16.7'
        Helm2.7.0:
          helm.version: '2.16.7'
        # default: 
        #   helm.version: 'latest'
    steps:
    - template: templates/helm-installer.yml
      parameters:
        helmVersion: $(helm.version)