parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test 
  - name: allValues
  - name: AGENT_USE_NODE10
    value: true

stages:
- stage: 'Ubuntu_2004'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)

- stage: 'Ubuntu_2204'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-22.04'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)

- stage: 'Win2019'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)

- stage: 'Win2022'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)

- stage: 'MacOS_Public_Catalina'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-10.15'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)

- stage: 'MacOS_Public_BigSur'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-11'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)

- stage: 'MacOS_Public_Monterey'
  jobs:
  - job: 'NugetInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-12'
    strategy:
      matrix:
        Nuget3.3.0:
          nuget.version: '4.0.0.2283'
        Nuget3.5.0:
          nuget.version: '3.5.0.1829'
        Nuget4.0.0:
          nuget.version: '4.0.0.2283'
    steps:
    - template: src/msbuild/nuget-installer.yml
      parameters:
        nugetVersion: $(nuget.version)