jobs:
  - job: 'Win2022s'
    displayName: Windows VS2022
    pool:
      name: 'Default'
    steps:
      # - template: src/msbuild/msbuild-steps.yml
      #   parameters:
      #     solutionPath: '$(build.sourcesdirectory)/src/msbuild/projects/SimpleConsoleAppCore3/SimpleConsoleAppCore3.sln'
      # - template: src/msbuild/msbuild-steps.yml
      #   parameters:
      #     solutionPath: '$(build.sourcesdirectory)/src/msbuild/projects/SimpleConsoleAppCore2/TestConsoleApp.sln'
      - task: PowerShell@2
        inputs:
          targetType: 'inline'
          script: |
            try {
              Write-Error 'This should go to hell. No one should care' 2>$null;
            } finally {
              exit 0;
            }
          failOnStderr: false