# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

# trigger:
  # enabled: false
stages:
- stage: __default
  jobs:
  - job: Job
    pool: 'mac-mini-pool'
      # vmImage: 'windows-2019'
    #'mac-mini-pool'
    steps:
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
    - task: CmdLinePre@2
      inputs:
        script: |
          echo $(Agent.BuildDirectory) && 
          cd $(Agent.BuildDirectory) &&
          ls && 
          cd _work &&
          ls

    - task: DownloadSecureFile@1
      name: caCertificate
      displayName: 'Download CA certificate'
      inputs:
        secureFile: 'test_file.txt'
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          echo $(caCertificate.secureFilePath)
          cat $(caCertificate.secureFilePath)