parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: ADO_FORCE_USE_PSUNZIP
    value: true
pool: #Default
  vmImage: 'windows-latest'

steps:
  - task: TokenizeInArchiveTask@1
    displayName: 'ReplaceToken #[]# in appsettings.test.json'
    inputs:
      PathToArchives: archs\*.zip
      Packages: '*.zip'
      FilesToTokenize: appsettings.test.json
      Prefix: '#['
      Suffix: ']#'
      ReplaceWithEmpty: false
  - task: AzureRmWebAppDeployment@4
    displayName: Webhooks-Legacy
    inputs:
      azureSubscription: 'CIX_Eng (371d9573-3b58-46e5-8489-aac909ffc94c)'
      appType: webApp
      WebAppName: vbobreshev-test-web-app
      deployToSlotOrASE: true
      ResourceGroupName: v-bobreshev-rg
      packageForLinux: archs\*.zip
      xmlVariableSubstitution: True
      enableCustomDeployment: true
      removeAdditionalFilesFlag: True
      takeAppOfflineFlag: True
      appOffline: True
      connectionType: AzureRM
      slotName: production