name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00'

stages:
- stage: 'ArchiveFilesWin2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  jobs:
    - job: 'TestInCorrect'
      displayName: 'Test incorrect checkout'
      steps:
        - checkout: self
          path: s/
        - checkout: git@github.com:elastic/logstash.git
          path: s/roles/logstash
          clean: false

    - job: 'TestCorrect'
      displayName: 'Test correct checkout'
      steps:
        - checkout: git@github.com:elastic/logstash.git
          path: s/roles/logstash
          clean: false
        - checkout: self
          path: s/