# resources:

#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"

    
    
stages:
  - stage: 'Ubuntu_2204'
    dependsOn: []
    jobs:
    - job: 'NugetInstall'
      pool:
        name: 'Azure Pipelines'
        vmImage: 'ubuntu-22.04'
      steps:
      - script: |
          echo 'console.log(process.argv.map(e => e.split("")))' > script.js
          node ./script.js $SECRET $NOSECRET
        env: 
          SECRET: $(SECRET) 
          NOSECRET: $(NOSECRET) 
      - task: JavaToolInstaller@0
        inputs:
          versionSpec: '8'
          jdkArchitectureOption: 'x64'
          jdkSourceOption: 'AzureStorage'
          azureResourceManagerEndpoint: 'martinmrazik Dev Environment(0031e7b5-6649-4025-b90d-e428f8ad69d8)'
          azureStorageAccountName: 'icm374740842testsa1000'
          azureContainerName: 'v-bobreshevd-java-container'
          azureCommonVirtualFile: 'jdk-20_linux-x64_bin.deb'
          jdkDestinationDirectory: '~./'
          cleanDestinationDirectory: false