jobs:

  - job: 'Win2019'
    displayName: Self Hosted Debian
    pool:
      name: 'win-11-pool'
      demands:
        - Agent.Name -equals debian-agent
    steps:
      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.10.5'
      
      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.5.1'

      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.10.5'