variables:
  - name: ndkPath
    value: C:\Android\android-sdk\ndk\23.2.8568313
  - name: androidSdkPath
    value: TEST_SDK_PATH

jobs:
  - job: 'Ubuntu_1804'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-180.04'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'Ubuntu_2004'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'Ubuntu_2204'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-22.04'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'Win2019'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'Win2022'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2022'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'MacOS_Public_Catalina'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-10.15'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'MacOS_Public_BigSur'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-11'
    steps:
    - template: src/python-script/templates/python-script-steps.yml
  
  - job: 'MacOS_Public_Monterey'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'macos-12'
    steps:
    - template: src/python-script/templates/python-script-steps.yml