# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"
  - name: AZP_75787_ENABLE_NEW_LOGIC_LOG
    value: true
  - name: AZP_75787_ENABLE_NEW_LOGIC
    value: true
  - name: AZP_75787_ENABLE_COLLECT
    value: true

jobs:
  - job:
    pool: #'agentvmsspool'
      vmImage: 'windows-latest'
    steps: 
      - task: AzureRmWebAppDeployment@4
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: 'CIX_Eng (371d9573-3b58-46e5-8489-aac909ffc94c)'
          appType: 'webApp'
          WebAppName: 'vbobreshev-test-web-app'
          packageForLinux: '$(System.DefaultWorkingDirectory)/**/site.zip'
          UseWebDeploy: true
          AdditionalArguments: -skip:objectName=filePath,absolutePath="^.*\.config$" -skip:objectName=filePath,absolutePath="favicon.ico" -skip:objectName=filePath,absolutePath="appsettings.json" -skip:objectName=dirPath,absolutePath='"${{ parameters.skipFolder }}"'