parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
pool:
  vmImage: 'windows-latest'



steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.13.0'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '18.13.0'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '6.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '8.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '10.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '14.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '16.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '12.x'
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '19.x'

  
  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: 'scripts/'
      ArtifactName: 'test'
      publishLocation: 'Container'
  - task: DownloadBuildArtifacts@1
    inputs:
      buildType: 'current'
      downloadType: 'single'
      artifactName: 'test'
      downloadPath: '$(System.ArtifactsDirectory)'