variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: node
    image: node:latest
    options: --name node-test
  - container: ubuntucontainer
    image: sitespeedio/node:ubuntu-20.04-nodejs-12.14.1
    options:  --name ubuntu-test

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool: Default

  container: ubuntucontainer
  services:
    ubuntucontainer: ubuntucontainer
  steps:
  - script: |
      docker ps
    target: host

  - script: |
      cat /etc/hostname
    target: node

  - script: 
      cat /etc/hostname
    target: ubuntucontainer