variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 

pool: 
  vmImage: windows-latest

steps:
  - task: AzureCLI@2
    inputs:
      azureSubscription: 'AzureDevOps_test'
      scriptType: 'ps'
      scriptLocation: 'inlineScript'
      inlineScript: 'echo "123"'