jobs:
  - job: 'Win2022s'
    displayName: Windows VS2022
    pool:
      vmImage: windows-2022
    steps:
      - powershell: echo $env:NDK_ROOT
      - bash: echo "##vso[task.setvariable variable=NDK_ROOT]TEST_NDK_ROOT"
      - powershell: echo $env:NDK_ROOT