variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    value: true

jobs:
- job: 'AzureVM_Ubuntu_Queue'
  displayName: AzureVM_Ubuntu_Queue
  pool: 
    name: 'Default'
    demands:
      - Agent.Name -equals debian
  steps:
    - template: src/jenkins/queue-job/test-queue-job.yml