parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: windows-latest

# container:
#   image: alpine:latest
#   endpoint: private_dockerhub_connection

jobs:
- job: 
  steps:
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureDevOps_test'
      ScriptType: 'InlineScript'
      Inline: 'Install-Module -Name Az.Resources -force'
      preferredAzurePowerShellVersion: '11.3.0'
      pwsh: true
  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureDevOps_test'
      ScriptType: 'InlineScript'
      Inline: 'echo hello'
      azurePowerShellVersion: 'OtherVersion'
      preferredAzurePowerShellVersion: '11.3.0'
      pwsh: true

  - task: AzurePowerShell@5
    inputs:
      azureSubscription: 'AzureDevOps_test'
      ScriptType: 'InlineScript'
      Inline: 'echo hello 2'
      azurePowerShellVersion: 'OtherVersion'
      preferredAzurePowerShellVersion: '9.6.0'
      pwsh: true