name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00'

stages:
- stage: 'ArchiveFilesWin2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  jobs:
    - job: 'TestInCorrect'
      displayName: 'Test incorrect checkout'
      steps:
        - task: PowerShell@2
          displayName: 'Check envs'
          env:
            ANDROID_HOME: 'TEST_ANDROID_HOME'
            NDK_ROOT: 'TEST_NDK_ROOT'
            ANDROID_NDK_HOME: 'TEST_ANDROID_NDK_HOME'
          inputs:
            targetType:  'inline'
            script: echo $NDK_ROOT; echo $ANDROID_NDK_HOME; echo $ANDROID_HOME