# resources:


#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
- name: solutionTarget
  type: string
  default: 'someSolutionTarget'
- name: msBuildArguments
  type: string
  default: 'argspassed'
- name: binSourcePath
  type: string
  default: ''

variables:
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: agent.diagnostic
    value: true
  - name: test
    value: $(Build.SourcesDirectory)
  - name: msBuildArgumentsVar
    value: ${{ coalesce(parameters.msBuildArguments, format('-target:{0}', parameters.solutionTarget)) }}
  - name: binSourcePath
    value: ${{ coalesce(parameters.binSourcePath, format('{0}/{1}/bin', variables.test, parameters.solutionTarget )) }}

jobs:
- job: 'Example'
  pool:
    # name: 'Default'
    vmImage: 'ubuntu-22.04'
  steps:
  - script: | 
      echo "msBuildArgumentsVar: $(msBuildArgumentsVar)" 
      echo "binSourcePath: $(binSourcePath)" 
      echo "test: $(test)"