variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 

pool: #Default 
  vmImage: windows-latest

jobs: 
  - job: Job1
    steps:
      - checkout: self
        clean: true
      # - task: DotNetCoreCLI@2
      #   inputs:
      #     command: 'push'
      #     packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      #     nuGetFeedType: 'internal'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "^3.13.0-0"
          architecture: "x64"
          allowUnstable: true
        displayName: "Use Python 3.13.0-rc.2 x64"
  - job: Job2
    dependsOn: Job1
    steps: 
      - checkout: self
        clean: true
        persistCredentials: true

      - script: eho "123" 