variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test


jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'macOS-latest'

  steps:
  - script: |
      echo "while (true) { }" >> test.js;
      node test.js