name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00'

stages:
- stage: 'ArchiveFilesWin2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  jobs:
    - deployment: VMDeploy
      displayName: Deploy to VM
      environment: 
        name: аываываыва
        resourceType: VirtualMachine
      strategy:
        runOnce:
          deploy:   
              steps:
              - powershell: echo $(get-process)
              - script: echo $(pwd)
              - bash: echo $(pwd)
        