# resources:


#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
- name: solutionTarget
  type: string
  default: 'someSolutionTarget'
- name: msBuildArguments
  type: string
  default: ''
- name: binSourcePath
  type: string
  default: ''

variables:
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: agent.diagnostic
    value: true
  - name: msBuildArgumentsVar
    value: ${{ coalesce(parameters.msBuildArguments, format('-target:{0}', parameters.solutionTarget)) }}
  - name: binSourcePath
    value: ''

jobs:
- job: 'NugetInstall'
  pool:
    # name: 'Default'
    vmImage: 'ubuntu-22.04'
  steps:
  - script: | 
      echo "msBuildArgumentsVar: $(msBuildArgumentsVar)" 
      echo "binSourcePath: $(binSourcePath)" 