trigger: none
pr: none
schedules:
- cron: '0 1 * * *'
  displayName: 'Nightly build (UTC)'
  always: 'true'
  branches:
    include:
    - main

variables:
- name: 'scriptDirectory'
  value: '$(Build.SourcesDirectory)/windows'

jobs:
- job: powerShellCore
  displayName: 'PowerShell Core Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - pwsh: |
      Write-Output $PSVersionTable | Select-Object -Property OS, Platform | Format-List
    displayName: Get PowerShell version
  - pwsh: |
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Default
    workingDirectory: '$(scriptDirectory)'
  - pwsh: |
      $ProgressPreference = 'SilentlyContinue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: SilentlyContinue
    workingDirectory: '$(scriptDirectory)'
  - pwsh: |
      $ProgressPreference = 'Continue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Continue
    workingDirectory: '$(scriptDirectory)'
- job: windowsPowerShell
  displayName: 'Windows PowerShell Progress Preference'
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      Write-Output $PSVersionTable | Select-Object -Property OS, Platform | Format-List
    displayName: Get PowerShell version
  - powershell: |
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Default
    workingDirectory: '$(scriptDirectory)'
  - powershell: |
      $ProgressPreference = 'SilentlyContinue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: SilentlyContinue
    workingDirectory: '$(scriptDirectory)'
  - powershell: |
      $ProgressPreference = 'Continue'
      .\powershell-progress-preference.ps1 -TempDirectory $(Build.ArtifactStagingDirectory)
    displayName: Continue
    workingDirectory: '$(scriptDirectory)'