variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: 'Debian'
  displayName: Debian
  pool:
    name: 'default'
    demands: 
      - Agent.Name -equals test200
  steps:
    - task: JenkinsQueueJob@1
      displayName: 'Queue Jenkins Job: Parameterized'
      inputs:
        serverEndpoint: 'ABTT_JenkinsContainer'
        jobName: 'BuildCanary_Parameterized'
        jobParameters: |
          MyBoolean=True
          MyString=TestString123
      retryCountOnTaskFailure: 3 
