parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: allValues

pool: 
  vmImage: 'ubuntu-latest'

stages:
- stage: A
  variables:
    - group: sampleGroup1
  jobs:
  - job: A1
    steps: 
      - script: |
          echo $(azureServiceConnectionGroup2);
          echo $(azureServiceConnectionGroup1);

- stage: B
  variables:
    - group: sampleGroup2
  jobs:
  - job: B1
    steps: 
      - script: |
          echo $(azureServiceConnectionGroup2);
          echo $(azureServiceConnectionGroup1);