parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: 'ubuntu-latest'

jobs:
- job: fine
  steps:
    - pwsh: |
        Write-Host "##vso[task.logissue type=error]The fourth thing went wrong."
        Write-Host "##[group]Group"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Host "##[endgroup]"
      displayName: Log Issue After Group
- job: broken
  steps:
    - pwsh: |
        Write-Host "##[group]Group"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Host "##[endgroup]"
        Write-Host "##vso[task.logissue type=error]The fourth thing went wrong."
      displayName: Log Issue After Group