# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: false
  - name: ARGS
    value: "123"
  - name: AZP_75787_ENABLE_NEW_LOGIC_LOG
    value: true
  - name: AZP_75787_ENABLE_NEW_LOGIC
    value: true
  - name: AZP_75787_ENABLE_COLLECT
    value: true
  - name: AGENT_USE_NODE10
    value: false

jobs:
  - job:
    pool: #'agentvmsspool'
      name: 'Default'
    steps: 
      - task: UseDotNet@2.222.0
        inputs:
          packageType: 'sdk'
          version: '7.x'