variables:
  NODE_OPTIONS: --max_old_space_size=2048

stages:
- stage: __default
  pool:
    vmImage: ubuntu-latest
  jobs:
  - job: 'DebianWSL'
    displayName: Show group and id inside WSL
    steps:
      - script: echo UID:$(id -u), GUID:$(id -g)
      - task: DownloadPackage@1
        inputs:
          packageType: maven
          feed: testFeed
          #view: ' ' # Optional
          definition: myPackage
          version: '1.0.0'
          downloadPath: ./test