parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'
  - name: deploy_all_tasks
    displayName: Build all tasks for deployment
    type: boolean
    default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: 'macos-latest'

stages:
- stage: first_stage
  jobs:
  - job:
    steps:
      # - task: IpaResign@1
      #   inputs:
      #     ipaPath: 'asdasd'
      #     entitlementsPath: 'ddsasd'
      #     signFileP12Path: 'asdads'
      #     signFileP12Password: 'asdasd'
      #     provFileProfilePath: 'asdasd'
      # - task: AppStoreRelease@1
      #   inputs:
      #     authType: 'ApiKey'
      #     apiKeyId: 'asd'
      #     apiKeyIssuerId: 'asdasd'
      #     apitoken: 'asdasdasd'
      #     apiKeyInHouse: true
      #     releaseTrack: 'TestFlight'
      #     distributeOnly: true
      #     appIdentifier: '123'
      #     appBuildNumber: '321'
      #     externalTestersGroups: 'asdf'
      - task: AppStorePromote@1
        inputs:
          authType: 'UserAndPass'
          username: 'bobresh95@gmail.com'
          password: '1234123132'
          isTwoFactorAuth: true
          appSpecificPassword: '123414'
          fastlaneSession: 'asdffas'
          appIdentifier: 's123dasqweqweqw'