variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test


jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'macOS-latest'

  steps:
  - bash: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_14.0.1.app/Contents/Developer"'
    displayName: 'Set Xcode 14.0.1 as default'

  - script: |
      xcodebuild -version
      swift -version

  - bash: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_14.0.app/Contents/Developer"'
    displayName: 'Set Xcode 14.0 as default'

  - script: |
      xcodebuild -version
      swift -version
  
  - bash: '/bin/bash -c "sudo xcode-select -s /Applications/Xcode_14.1.app/Contents/Developer"'
    displayName: 'Set Xcode 14.1 as default'

  - script: |
      xcodebuild -version
      swift -version