name: $(SourceBranchName)_$(Date:yyyyMMdd)

variables:
#   - name: System.Debug
#     value: true
#   - name: build.clean
#     value: all
#   - name: agent.clean.buildDirectory
#     value: all
#   - name: buildPlatform
#     value: 'Any CPU'
#   - name: buildConfiguration
#     value: 'UNIT_TEST'
#   - name: AGENT_USE_NODE10
#     value: true
  - name: BuildNameTest
    value: 'ubuntu-build-number-1' 
      
jobs:
  - job: macos_test
    pool:
        name: Default
        # vmImage: macos-latest
    steps:
    - task: npmAuthenticate@0
      inputs:
        workingFile: .npmrc
      condition: eq('false', 'true')