parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test 
  - name: allValues
  # - name: AGENT_USE_NODE10
  #   value: true

stages:
- stage: 'Ubuntu_2004'
  dependsOn: []
  jobs:
  - job: 'OpaInstall'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-20.04'
    strategy:
      matrix:
        Opa0.46.1:
          opa.version: '0.46.1'
        Opa0.41.0:
          opa.version: '0.41.0'
        Opa0.30.2:
          opa.version: '0.30.2'
        Opa0.21.0:
          opa.version: '0.21.0'
    steps:
    - template: templates/openpolicy.yml
      parameters:
        opaVersion: $(opa.version)

# - stage: 'Ubuntu_2204'
#   dependsOn: []
#   jobs:
#   - job: 'OpaInstall'
#     pool:
#       name: 'Azure Pipelines'
#       vmImage: 'ubuntu-22.04'
#     steps:
#     - template: templates/openpolicy.yml
#       parameters:
#         opaVersion: $(opa.version)

# - stage: 'Win2019'
#   dependsOn: []
#   jobs:
#   - job: 'OpaInstall'
#     pool:
#       name: 'Azure Pipelines'
#       vmImage: 'windows-2019'
#     steps:
#     - template: templates/openpolicy.yml
#       parameters:
#         opaVersion: $(opa.version)

# - stage: 'Win2022'
#   dependsOn: []
#   jobs:
#   - job: 'OpaInstall'
#     pool:
#       name: 'Azure Pipelines'
#       vmImage: 'windows-2022'
#     steps:
#     - template: templates/openpolicy.yml
#       parameters:
#         opaVersion: $(opa.version)

# - stage: 'MacOS_Public_Catalina'
#   dependsOn: []
#   jobs:
#   - job: 'OpaInstall'
#     pool:
#       name: 'Azure Pipelines'
#       vmImage: 'macos-10.15'
#     steps:
#     - template: templates/openpolicy.yml
#       parameters:
#         opaVersion: $(opa.version)

# - stage: 'MacOS_Public_BigSur'
#   dependsOn: []
#   jobs:
#   - job: 'OpaInstall'
#     pool:
#       name: 'Azure Pipelines'
#       vmImage: 'macos-11'
#     steps:
#     - template: templates/openpolicy.yml
#       parameters:
#         opaVersion: $(opa.version)

# - stage: 'MacOS_Public_Monterey'
#   dependsOn: []
#   jobs:
#   - job: 'OpaInstall'
#     pool:
#       name: 'Azure Pipelines'
#       vmImage: 'macos-12'
#     steps:
#     - template: templates/openpolicy.yml
#       parameters:
#         opaVersion: $(opa.version)