# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"
  - name: AGENT_USE_NODE10
    value: true
  - name: VSTSAGENT_DUMP_JOB_EVENT_LOGS
    value: true
  - name: coverageFilePath
    value: test

jobs:
  - job:
    pool: #'agentvmsspool'
      #name: 'Default'
      vmImage: 'ubuntu-latest'
    steps: 
      - task: UseDotNet@2
        inputs:
          packageType: 'sdk'
          version: '8.x'
          includePreviewVersions: true
      - script: dotnet --info
      - script: dotnet tool restore
        displayName: Restore tools
      - script: dotnet coverage merge outputs/coverage/ -r -f cobertura -o $(coverageFilePath)
        displayName: Merge coverage files