stages:
  # - stage: 'MacOS_Public_Catalina'
  #   dependsOn: []
  #   jobs:
  #   - job: 'App1'
  #     pool:
  #       vmImage: 'macos-10.15'
  #     strategy:
  #       matrix:
  #         default:
  #         ios_14.14_mono_6.12_xcode_12.4:
  #           XAMARIN_SYMLINK: 6_12_7
  #           XCODE_VERSION: 12.4
  #           NETCORE_VERSION: 5.0.202
  #     steps:
  #     - template: src/xamarin-ios/templates/test-xamarin-ios-using-ui-test.yml
  #       parameters:
  #         XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
  #         XCODE_VERSION: $(XCODE_VERSION)
  #   - job: 'App2'
  #     pool:
  #       vmImage: 'macos-10.15'
  #     strategy:
  #       matrix:
  #         ios_14.14_mono_6.12_xcode_12.4:
  #           XAMARIN_SYMLINK: 6_12_7
  #           XCODE_VERSION: 12.4
  #           NETCORE_VERSION: 5.0.202
  #     steps:
  #     - template: src/xamarin-ios/templates/test-xamarin-ios-todo-list.yml
  #       parameters:
  #         XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
  #         XCODE_VERSION: $(XCODE_VERSION)
  #         NETCORE_VERSION: $(NETCORE_VERSION)
  
  - stage: 'MacOS_Public_BigSur'
    dependsOn: []
    jobs:
    - job: 'App1'
      pool:
        vmImage: 'macos-11'
      strategy:
        matrix:
          ios_15.8_mono_6.12_xcode_13.2.1:
            XAMARIN_SYMLINK: 6_12_16
            XCODE_VERSION: 13.2.1
            NETCORE_VERSION: 5.0.408
      steps:
      - template: src/xamarin-ios/templates/test-xamarin-ios-using-ui-test.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          XCODE_VERSION: $(XCODE_VERSION)
    - job: 'App2'
      pool:
        vmImage: 'macos-11'
      strategy:
        matrix:
          ios_15.8_mono_6.12_xcode_13.2.1:
            XAMARIN_SYMLINK: 6_12_16
            XCODE_VERSION: 13.2.1
            NETCORE_VERSION: 5.0.408
      steps:
      - template: src/xamarin-ios/templates/test-xamarin-ios-todo-list.yml
        parameters:
          XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
          XCODE_VERSION: $(XCODE_VERSION)
          NETCORE_VERSION: $(NETCORE_VERSION)
  
  # - stage: 'MacOS_Public_Monterey'
  #   dependsOn: []
  #   jobs:
  #   - job: 'App1'
  #     pool:
  #       vmImage: 'macos-12'
  #     strategy:
  #       matrix:
  #         ios_15.8_mono_6.12_xcode_13.3.1:
  #           XAMARIN_SYMLINK: 6_12_16
  #           XCODE_VERSION: 13.3.1
  #           NETCORE_VERSION: 5.0.408
  #     steps:
  #     - template: src/xamarin-ios/templates/test-xamarin-ios-using-ui-test.yml
  #       parameters:
  #         XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
  #         XCODE_VERSION: $(XCODE_VERSION)
  #   - job: 'App2'
  #     pool:
  #       vmImage: 'macos-12'
  #     strategy:
  #       matrix:
  #         ios_15.8_mono_6.12_xcode_13.3.1:
  #           XAMARIN_SYMLINK: 6_12_16
  #           XCODE_VERSION: 13.3.1
  #           NETCORE_VERSION: 5.0.408
  #     steps:
  #     - template: src/xamarin-ios/templates/test-xamarin-ios-todo-list.yml
  #       parameters:
  #         XAMARIN_SYMLINK: $(XAMARIN_SYMLINK)
  #         XCODE_VERSION: $(XCODE_VERSION)
  #         NETCORE_VERSION: $(NETCORE_VERSION)