name: $(TeamProject)_$(Build.DefinitionName)_$(SourceBranchName)_$(Date:yyyyMMdd)$(Rev:.r)

parameters:
  - name: applications_module
    displayName: Applications
    type: boolean
    default: 'false'
    values: []
  - name: management
    displayName: Management
    type: boolean
    default: 'false'
    values: []
  - name: It
    displayName: IT_module
    type: boolean
    default: 'false'
    values: []

variables:
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'UNIT_TEST'
  - name: AGENT_USE_NODE10
    value: true

      
jobs:
- job: Build
  pool:
    name: Azure Pipelines
    vmImage: ubuntu-latest

  steps:
  - bash: |
      echo "##vso[build.updatebuildnumber]my-new-build-number"
    displayName: 'Update Build Number'
  - task: Docker@2
    displayName: ' Build docker container'
    continueOnError: false
    inputs:
      command: build
      tags: 'latest'
      Dockerfile: './Dockerfile.text'