variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    value: true

jobs:
- job: 'Ubuntu_2004'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-20.04'
  steps:
  - template: src/gulp/test-gulp.yml

- job: 'Ubuntu_2204'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-22.04'
  steps:
  - template: src/gulp/test-gulp.yml

- job: 'Win2019'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
  - template: src/gulp/test-gulp.yml

- job: 'Azure Pipelines'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-10.15'
  steps:
  - template: src/gulp/test-gulp.yml

- job: 'MacOS_Public_BigSur'
  pool: 
    name: 'Azure Pipelines'
    vmImage: 'macos-11'
  steps:
  - template: src/gulp/test-gulp.yml

- job: 'MacOS_Public_Monterey'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-12'
  steps:
  - template: src/gulp/test-gulp.yml