# resources:
#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true
  - name: ARGS
    value: "123"
  - name: AZP_75787_ENABLE_NEW_LOGIC_LOG
    value: true
  - name: AZP_75787_ENABLE_NEW_LOGIC
    value: true
  - name: AZP_75787_ENABLE_COLLECT
    value: true

jobs:
  - job:
    pool: 
      vmImage: 'ubuntu-latest'
    steps: 
      - task: Bash@3
        continueOnError: true
        inputs:
          filePath: 'shell/test.sh'
          arguments: 'test & echo $(ARGS) & exec bash'
      - task: Bash@3
        continueOnError: true
        inputs:
          filePath: 'shell/test.sh'
          arguments: '--2 ; "12", , , ,,,, \s\s/sd, & bash'
      - task: Bash@3
        continueOnError: true
        inputs:
          filePath: 'shell/test.sh'
          arguments: '--2 ; "12", , , ,,,, \s\s/sd, & bash'
      - task: Bash@3
        continueOnError: true
        inputs:
          filePath: 'shell/test.sh'
          arguments: '--21 2 3 > whoami'