parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'
  - name: deploy_all_tasks
    displayName: Build all tasks for deployment
    type: boolean
    default: false

variables:
  - name: System.Debug
    value: false
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: Default
  #vmImage: 'ubuntu-latest'

stages:
- stage: first_stage
  jobs:
  - job: first_job
    pool: #Default
       vmImage: windows-latest
    steps:
    - pwsh: Write-Host "##vso[task.logissue type=error]The first thing went wrong."
      displayName: Log Issue Without Group
    - pwsh: |
        Write-Host "##vso[task.logissue type=error] Log Before Inside Group thing went wrong."
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Output "====== Filler ======"
        Write-Host "##[endgroup]"
      displayName: deploy_all_tasks_false
