variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true

# resources:
#   containers:
#   - container: my_container
#     image: node:latest
#   - container: nginx
#     image: nginx:latest


# pool: Default

# pool:
#     vmImage: 'ubuntu-latest'
 
# container:  ubuntu:18.04
# services:
  # nginx: nginx

# steps:
#   - script: |
#       cat /etc/hostname
#       export MY_ENV='test'
#       mkdir test
#       touch test/file_example
#   - script: |
#       cat /etc/hostname
#       sleep 10
#   - script: |
#       echo $MY_ENV
#       ls test

  

# --------------------------------------------------------------------------------------------------

pool: #Default
  name: 'Azure Pipelines'
  vmImage: windows-latest
steps:
- checkout: none
- bash: echo "process.exit('SIGINT');" > test.js
- script: node  test.js