parameters:
  - name: skipFolder
    type: string
    default: '^.*Resources(?!CL|Generic|\|$).*$'

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: 'windows-latest'

steps:
  - script: |
        echo "##vso[task.setvariable variable=task_pattern;isOutput=true;]somethingspecial"
    name: getTaskPattern
    displayName: setVariable getTaskPattern
  
  - script: |
      exho "getTaskPattern.task_pattern"
      echo $(getTaskPattern.task_pattern)
      echo "task_pattern"
      echo $(task_pattern)