name: '$(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00'

stages:
- stage: 'ArchiveFilesWin2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  jobs:
  - template: src\archive-files\templates\jobs-template.yml

- stage: 'ArchiveFilesHosted2017'
  displayName: Windows2019
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  jobs:
  - template: src\archive-files\templates\jobs-template.yml

- stage: 'ArchiveFiles_Ubuntu_1804'
  displayName: Ubuntu_1804
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-18.04'
  steps:
  - template: src\archive-files\templates\jobs-template.yml

- stage: 'ArchiveFiles_Ubuntu_2004'
  displayName: Ubuntu_2004
  pool:
    name: 'Azure Pipelines'
    vmImage: 'ubuntu-20.04'
  jobs:
  - template: src\archive-files\templates\jobs-template.yml

- stage: 'MacOS_Public_Catalina'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-10.15'
  jobs:
  - template: src\archive-files\templates\jobs-template.yml

- stage: 'MacOS_Public_BigSur'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'macos-11'
  jobs:
  - template: src\archive-files\templates\jobs-template.yml
