variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

stages:
  - stage: 'MacOS_Public_Catalina'
    dependsOn: [] 
    jobs:
    - template: 'src/installAppleProvisioningProfile/templates/install-prov-profile-jobs.yml'
      parameters:
        poolName: 'Azure Pipelines'
        vmImageName: 'macos-10.15'
  
  - stage: 'MacOS_Public_BigSur'
    dependsOn: []
    jobs:
    - template: 'src/installAppleProvisioningProfile/templates/install-prov-profile-jobs.yml'
      parameters:
        poolName: 'Azure Pipelines'
        vmImageName: 'macos-11'
  
  - stage: 'MacOS_Public_Monterey'
    dependsOn: []
    jobs:
    - template: 'src/installAppleProvisioningProfile/templates/install-prov-profile-jobs.yml'
      parameters:
        poolName: 'Azure Pipelines'
        vmImageName: 'macos-12'