variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH

jobs:
# - job: 'VS2019'
#   pool: $[ coalesce(variables.vs2019, 'Hosted Windows 2019 with VS2019') ]
#   steps:
#   - template: src/ftp-upload/templates/ftp-upload-test.yml
#     parameters:
#       rootFolderPrefix: vs2019

- job: 'Ubuntu_1804'
  pool: 'default'
  steps:
  - template: src/ftp-upload/templates/ftp-upload-test.yml
    parameters:
      rootFolderPrefix: ubuntu1804