variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: my_container
    image: node:latest
  - container: nginx
    image: nginx

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool: 'Default'
    # vmImage: 'ubuntu-latest'

  container: my_container
  services:
    nginx: nginx

  steps:
  # - script: |
  #     curl nginx
  #   displayName: Show that nginx is running
  - script: docker ps
    target: host
  - script: |
      cat /etc/hostname
    target: 
      container: nginx
  - script: |
      cat /etc/hostname
    target: 
      container: my_container
# - job: WaitForDocker
#   pool: 
#     vmImage: 'ubuntu-latest'
#   steps:
#     - restoreCache: myKey
#       path: .

#     - saveCache: myKey
#       path: .
#     - checkout: none
#     - bash: |
#         while (! docker stats --no-stream ); do
#           echo "Waiting for Docker to launch..."
#           sleep 1
#         done
# - job: DockerStarted
 
#   dependsOn: WaitForDocker 
#   steps:
#   - script: printenv