jobs:

  - job: 'Win2019'
    displayName: Self Hosted Debian
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
      - template: templates/use-python-version.yml
        parameters:
          pythonVersion: '3.10.1'