stages:
  - stage: 'Hosted_Ubuntu_2004'
    pool:
      vmImage: 'ubuntu-20.04'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipJdk12Build: true
        skipJdk13Build: true
  
  # - stage: 'Hosted_Ubuntu_2204'
  #   condition: and(succeeded(),  contains(variables.targetPools, 'Hosted Ubuntu 2204'))
  #   pool:
  #     name: 'Azure Pipelines'
  #     vmImage: 'ubuntu-22.04'
  #   dependsOn: []
  #   jobs:
  #   - template: ./src/gradle/templates/gradle-jobs.yml
  #     parameters:
  #       skipJdk12Build: true
  #       skipJdk13Build: true
  
  - stage: 'Win2016'
    pool:
      vmImage: 'vs2017-win2016'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipJdk12Build: true
  
  - stage: 'Win2019'
    pool:
      vmImage: 'windows-2019'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipJdk12Build: true
  
  - stage: 'Win2022'
    pool:
      vmImage: 'windows-2022'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipJdk12Build: true
        skipJdk13Build: true
        skipNativeMediaBuild: true
  
  - stage: 'MacOS_Public_Catalina'
    pool:
      vmImage: 'macos-10.15'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipNativeMediaBuild: true
  
  - stage: 'MacOS_Public_BigSur'
    pool:
      vmImage: 'macos-11'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipNativeMediaBuild: true
        skipJdk12Build: true
        skipJdk13Build: true
  
  - stage: 'MacOS_Public_Monterey'
    pool:
      vmImage: 'macos-12'
    dependsOn: []
    jobs:
    - template: ./src/gradle/templates/gradle-jobs.yml
      parameters:
        skipNativeMediaBuild: true
        skipJdk12Build: true
        skipJdk13Build: true