variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all

jobs:
- job: job1
  pool:
    vmImage: 'windows-latest'
  steps:
    - pwsh: |
        echo "123123"
      name: task
    - pwsh: |
        cd $(Agent.HomeDirectory);
        mkdir testjobfolder
        dir

- job: job2
  pool:
    vmImage: 'windows-latest'
  dependsOn:
    - job1
  variables:
    slotAppSettings: $[ dependencies.job1.outputs['task.value'] ]
  steps:
    - pwsh: |
        echo "MASKED:" $env:myvar;
        cd $(Agent.HomeDirectory);
        dir;
      env:
        myvar: $(slotAppSettings)