variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: nginx
    image: nginx
    options: --name nginx-test
    ports:
    - 8080:80
    env:
      NGINX_PORT: 80
  - container: ubuntucontainer
    image: node:latest
    options:  --name ubuntu-test

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool: Default

  container: nginx
  services:
    ubuntucontainer: ubuntucontainer
  steps:
  - script: |
      docker ps
    target: host

  - script: |
      cat /etc/hostname
    target: nginx

  - script: 
      cat /etc/hostname
    target: ubuntucontainer