variables:
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    value: true

stages:
- stage: 'Win'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Hosted Windows 2019 with VS2019'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2019'
  - job: InstallSSHKey_Windows
    displayName: 'Test InstallSSHKey on Windows'
    pool:
      name: 'Azure Pipelines'
      vmImage: 'windows-2019'
    steps:
    - template: templates/test-install-key.yml

- stage: 'Debian'
  dependsOn: []
  jobs:
  - template: src/agentTest/agent-test-installer-tasks-template.yml
    parameters:
      pool:
        name: 'Azure Pipelines'
        vmImage: 'windows-2022'
  - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
    parameters:
      targetPools: 'Hosted Ubuntu 1804'
      enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
      pool: 
        name: 'Azure Pipelines'
        vmImage: 'ubuntu-18.04'
  - job: InstallSSHKey_Debian
    displayName: 'Test InstallSSHKey on Debian'
    pool: 
      name: 'Azure Pipelines'
      vmImage: 'ubuntu-18.04'
    steps:
    - template: templates/test-install-key.yml

# - stage: 'Debian via container'
#   dependsOn: []
#   jobs:
#   - template: src/agentTest/agent-test-installer-tasks-container-template.yml
#     parameters:
#       pool: 
#         name: 'Azure Pipelines'
#         vmImage: 'ubuntu-18.04'

#   - template: src/javaToolInstaller/templates/java-tool-installer-jobs-template-jdk7.yml
#     parameters:
#       targetPools: 'Hosted Ubuntu 1804'
#       enableAzureResourcesDependentTests: ${{ variables.enableAzureResourcesDependentTests }}
#       pool: 
#         name: 'Azure Pipelines'
#         vmImage: 'ubuntu-18.04'

#   - job: InstallSSHKey_Debian
#     displayName: 'Test InstallSSHKey on Debian'
#     pool: 
#       name: 'Azure Pipelines'
#       vmImage: 'ubuntu-18.04'
#     container: debian:latest
#     steps:
#     - template: templates/test-install-key.yml
