parameters:
- name: enableCodeQL
  displayName: Enable CodeQL for run
  type: boolean
  default: false

variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: false
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 
  # - name: ADO_FORCE_USE_PSUNZIP
  #   value: true
pool: #Default
  vmImage: ubuntu-latest

# container:
#   image: alpine:latest
#   endpoint: private_dockerhub_connection

steps:
  - script: alias docker="null"
  - task: DockerCompose@0
    inputs:
      containerregistrytype: 'Azure Container Registry'
      dockerComposeFile: '**/docker-compose.yml'
      action: 'Run a Docker Compose command'