# resources:


#   repositories:
#   - repository: AzureDevOps
#     type: git
#     endpoint: AzureDevOps
#     name: AzureDevOps/AzureDevOps

parameters:
- name: solutionTarget
  type: string
  default: 'someSolutionTarget'
- name: msBuildArguments
  type: string
  default: ''
- name: binSourcePath
  type: string
  default: ''

variables:
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: agent.diagnostic
    value: true
  - name: sourceDir
    value: $(Build.SourcesDirectory)

jobs:
- job: 'Example'
  pool:
    # name: 'Default'
    vmImage: 'windows-latest'
  steps:
  
    - task: PackerBuild@1
      inputs:
        templateType: 'custom'
        customTemplateLocation: 'templates/script.ps1'
        packerVersion: '1.5.1'
  

  # - task: PackerBuild@1
  #   inputs:
  #     templateType: 'builtin'
  #     ConnectedServiceName: 'CIX_Eng (371d9573-3b58-46e5-8489-aac909ffc94c)'
  #     isManagedImage: false
  #     location: 'westus'
  #     storageAccountName: 'vbobreshevtestjavatask'
  #     azureResourceGroup: 'v-bobreshev-rg'
  #     baseImageSource: 'default'
  #     baseImage: 'MicrosoftWindowsServer:WindowsServer:2012-R2-Datacenter:windows'
  #     packagePath: 'templates'
  #     deployScriptPath: '**/script.ps1'
  # - task: Powershell@2
  #   displayName: 'Set Image'
  #   inputs:
  #     targetType: 'inline'
  #     script: |
  #       # echo "##vso[task.setvariable variable=JAVA$(javaImageEnv)IMAGE]java$(javaImageEnv)image"
  #       # export JAVA$(javaImageEnv)IMAGE=java$(javaImageEnv)image
  #       echo '123'

  # - task: Bash@3
  #   displayName: 'Test Images Part 1'
  #   inputs:
  #     enable_network : true
  #     targetType: 'inline'
  #     script: |
  #       # echo JAVA$(javaImageEnv)IMAGE = $JAVA$(javaImageEnv)IMAGE
  #       echo JAVA8_zuluIMAGE = $JAVA8_zuluIMAGE