# variables:
#  - name: task
#    value: MSBuildV1

# jobs:

# # All tasks on Windows
# - job: build_all_windows
#   displayName: Build all tasks (Windows)
#   condition: and(succeeded(), not(variables.task), eq(variables.os, 'Windows_NT'))
#   pool: win-11-pool
#   timeoutInMinutes: 120
#   steps:
#   - template: ci/build-all-steps.yml
#     parameters:
#       os: Windows_NT

# # All tasks on Linux
# - job: build_all_linux
#   displayName: Build all tasks (Linux)
#   condition: and(succeeded(), not(variables.task), eq(variables.os, 'Linux'))
#   pool:  win-11-pool
#   steps:
#   - template: ci/build-all-steps.yml
#     parameters:
#       os: Linux

# # Single task
# - job: buildSingle
#   displayName: Build single task
#   condition: and(succeeded(), variables.task)
#   pool: 
#     vmImage: windows-latest
#   steps:
#   - template: ci/build-single-steps.yml

# # Single task
# - job: buildSingle
#   displayName: Build single task
#   condition: and(succeeded(), variables.test)
#   pool:
#     vmImage: windows-2022
#   steps:
#   # Verify min agent version demands
#   - script: |
#     cd ci
#     cd verifyMinAgentDemands
#     npm install
#     node index.js
#   displayName: Verify all min agent demands are valid


# Starter pipeline


# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
  NODE_OPTIONS: --max_old_space_size=2048

stages:
- stage: __default
  jobs:
  - job: Job
    pool: win-11-pool
      # vmImage: windows-2019
    steps:
    - task: DownloadSecureFile@1
      name: caCertificate
      displayName: 'Download CA certificate'
      inputs:
        secureFile: 'test.js'
    - task: DownloadSecureFile@1
      name: BigFileTest
      displayName: 'Download Big File'
      inputs:
        secureFile: '1.txt'
    - task: CmdLine@2
      displayName: 'Run a one-line script'
      inputs:
        script: echo Hello, world!
    - task: CmdLine@2
      displayName: 'Run a multi-line script'
      inputs:
        script: |
          echo Add other tasks to build, test, and deploy your project.
          echo See https://aka.ms/yaml
    # - task: CmdLine@2
    #   displayName: 'Run a multi-line script'
    #   inputs:
    #     script: |
    #       node $(caCertificate.secureFilePath)
    # - task: NodeTool@0
    #   displayName: Use node 8
    #   inputs:
    #     versionSpec: "8.x"
    - script: echo null > test.txt
      displayName: 'Creating file'

    - task: CopyFiles@2
      inputs:
        Contents: test.txt
        TargetFolder: 'testFolder'
      displayName: 'Try to run commund under node10'
    - task: NodeTool@0
      inputs:
        versionSpec: 'v14.17.1'
      displayName: 'Install Node.js v14.17.1'
    
    - script: 'npm -v'
      displayName: Show npm version Before
    - script: 'echo %PATH%'
      displayName: Show PATH
    - task: Npm@1
      displayName: Install npm 7.21.1
      inputs:
        command: 'custom'
        customCommand: 'install --global --force npm@7.21.1'
    # - powershell: |
    #     npm bin -g | pushd
    #     del npm, npm.cmd, npx, npx.cmd
    #     move node_modules\npm node_modules\npm2
    #     node node_modules\npm2\bin\npm-cli.js i npm@7.21.1 -g
    #     Remove-Item 'node_modules\npm2' -Force -Recurse
    #     popd
    #   displayName: Use npm version 7.21.1
    - script: 'npm -v'
      displayName: Show npm version After
      