variables:
  - group: secrets-groups
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
  - name: agent.diagnostic
    value: true

# resources:
#   containers:
#   - container: my_container
#     image: node:latest
#   - container: nginx
#     image: nginx:latest


# pool: Default

# pool:
#     vmImage: 'ubuntu-latest'
 
# container:  ubuntu:18.04
# services:
  # nginx: nginx

# steps:
#   - script: |
#       cat /etc/hostname
#       export MY_ENV='test'
#       mkdir test
#       touch test/file_example
#   - script: |
#       cat /etc/hostname
#       sleep 10
#   - script: |
#       echo $MY_ENV
#       ls test

  

# --------------------------------------------------------------------------------------------------

pool: #Default
  name: 'Azure Pipelines'
  vmImage: windows-latest
steps:
- checkout: none
- bash: echo "process.exit('SIGINT');" > test.js
- script: node  test.js
- task: JavaToolInstaller@0
  displayName: 'Use Java 1.7'
  inputs:
    versionSpec: '7'
    jdkArchitectureOption: 'x64'
    jdkSourceOption: 'AzureStorage'
    azureResourceManagerEndpoint: 'ABTT_JAVA_Test'
    azureStorageAccountName: 'abttcanarystorageaccount'
    azureContainerName: 'java-distribution'
    azureCommonVirtualFile: 'folder/sub-7-azure-jdk_7.24.0.2-7.0.191-win_x64.zip'
    jdkDestinationDirectory: './tempAzure'
    cleanDestinationDirectory: true