variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: my_container
    image: buildpack-deps:focal
  - container: nginx
    image: nginx

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool: #'Default'
    vmImage: 'ubuntu-latest'

  container: my_container
  services:
    nginx2: nginx

  steps:
  - script: |
      curl nginx2
    displayName: Show that nginx is running
  - script: docker ps
    target: host

  - script: cat /etc/hostname
    target:
        container: nginx
  - script: cat /etc/hostname
    target:
      container: my_container

# - job: example
#   pool: 'Default'
#   container: my_container

#   steps:
#   - script: docker ps
#     target: host

#   - script: cat /etc/hostname
#     target:
#         container: nginx

#   - script: cat /etc/hostname
#     target:
#       container: my_container