variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH

jobs:
- job: 'Debian'
  displayName: Debian
  pool:
    name: 'default'
  steps:
    - script: |
        ls -la
        echo '123'
