variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: false
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test
resources:
  containers:
  - container: ubuntucontainer
    image: ubuntu
    options: --hostname ubuntu-test --name ubuntu-test
  - container: nginx
    image: nginx
    options: --hostname nginx-test --name nginx-test
    ports:
    - 8080:80
    env:
      NGINX_PORT: 80

jobs:
- job: integration_tests
  displayName: Run integration tests
  pool:
    vmImage: 'ubuntu-latest'

  steps:
  - script: |
      docker ps
      $IP = docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' nginx-test
      echo $IP
      echo "##vso[task.setvariable variable=nginx-test-ip;]$IP"
    target: host
  
  - script: |
      # curl 127.0.0.2:8080
      curl $(nginx-test-ip):8080

  - script: 
      cat /etc/hostname
    target:
        container: nginx
  
  - script: | 
      cat /etc/hostname
      # curl 192.168.0.1:8080
      curl nginx-test:8080
    target:
      container: ubuntucontainer

# - job: example
#   pool: 'Default'
#   container: my_container

#   steps:
#   - script: docker ps
#     target: host

#   - script: cat /etc/hostname
#     target:
#         container: nginx

#   - script: cat /etc/hostname
#     target:
#       container: my_container