jobs:

- job: 'Win2019'
  displayName: Windows VS2019
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  steps:
    - powershell: wget https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip  

- job: 'Win2022'
  displayName: Windows VS2022
  pool:
    name: 'win-11-pool'
  steps:
    - powershell: wget https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip  