stages:
  # - stage: 'Hosted_Ubuntu_2004'
  #   pool:
  #     vmImage: 'ubuntu-20.04'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'Hosted_Ubuntu_2204'
  #   pool:
  #     name: 'Azure Pipelines'
  #     vmImage: 'ubuntu-22.04'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'Win2016'
  #   pool:
  #     vmImage: 'vs2017-win2016'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'Win2019'
  #   pool:
  #     vmImage: 'windows-2019'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'Win2022'
  #   pool:
  #     vmImage: 'windows-2022'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'MacOS_Public_Catalina'
  #   pool:
  #     vmImage: 'macos-10.15'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'MacOS_Public_BigSur'
  #   pool:
  #     vmImage: 'macos-11'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'
  
  # - stage: 'MacOS_Public_Monterey'
  #   pool:
  #     vmImage: 'macos-12'
  #   dependsOn: []
  #   jobs:
  #   - job:
  #     steps:
  #     - task: DownloadSecureFile@1
  #       name: caCertificate
  #       displayName: 'Download CA certificate'
  #       inputs:
  #         secureFile: 'test.js'
  #     - script: node $(caCertificate.secureFilePath)
  #     - task: DownloadSecureFile@1
  #       name: BigFileTest
  #       displayName: 'Download Big File'
  #       inputs:
  #         secureFile: '1.txt'

  - stage: 'default'
    dependsOn: []
    jobs:
    - job: job1
      pool:
        name: 'Default'
        # vmImage: 'macos-12'
      timeoutInMinutes: 5
      steps:
      - task: DownloadSecureFile@1
        name: caCertificate
        displayName: 'Download CA certificate'
        inputs:
          secureFile: 'test.js'
      - script: node $(caCertificate.secureFilePath)
      - task: DownloadSecureFile@1
        name: BigFileTest
        displayName: 'Download Big File'
        inputs:
          secureFile: '1.txt'
    - job: job2
      dependsOn: job1
      condition: failed()
      pool:
        # name: 'Default'
        vmImage: 'macos-12'
      steps:
        - script: echo "This job will run only if job1 fails"