variables:
  - name: ndkPath
    value: TEST_NDK_PATH
  - name: androidSdkPath
    value: TEST_SDK_PATH
  - name: System.Debug
    value: true
  - name: build.clean
    value: all
  - name: agent.clean.buildDirectory
    value: all
  - name: scheme
    value: test

jobs:
- job: job1
  pool:
      vmImage: 'ubuntu-latest'
  steps:
    - script: |
        echo '123'
        exit 1
    - script: echo 'second Step'
