variables:
  - name: System.Debug
    value: true
  - name: Agent.Diagnostic
    value: true
  - name: sometextprobably 
    value: 'fear'
  - name: currentDate
    value:  $[ format('{0:yyyy}{0:MM}{0:dd}', pipeline.startTime) ]
  - name: skipScanDir
    value: true 

pool: #Default 
  vmImage: windows-latest

jobs: 
  - job: Job1
    steps:
      - task: SSH@0
        inputs:
          sshEndpoint: 'test_ssh'
          runOptions: 'inline'
          interactiveSession: true
          inline: |
            sudo su - dmybor
            echo "example String"> logFile.log
            log_result=$(cat logFile.log)
            echo $log_result > result.txt
            cat result.txt
          readyTimeout: '20000'

      - task: UsePythonVersion@0
        inputs:
          versionSpec: "^3.13.0-0"
          architecture: "x64"
          allowUnstable: true
        displayName: "Use Python 3.13.0-rc.2 x64"
