parameters:
- name: testOptions
  displayName: Test Options
  type: object
  default:
    - refs/heads/main
    - refs/heads/test

variables:
  NODE_OPTIONS: --max_old_space_size=2048
  insert: script

stages:
- stage: __default
  pool:
    name: 'default'
    demands:
      - Agent.Name -equals win-11
  jobs:
  - job: 'DebianWSL'
    displayName: Show group and id inside WSL
    steps:
      - ${{ each value in parameters.testOptions }}:
        - script: echo ${{ value }}
      - script: echo UID:$(id -u), GUID:$(id -g)
      - task: DownloadPackage@1
        inputs:
          packageType: npm
          feed: 4098af9f-9bef-4a67-8087-64b5d95a7597/2da201f0-f31e-4084-851f-bb8babd17e4e
          #view: ' ' # Optional
          definition: test
          version: '1.0.0'
          downloadPath: ./test