parameters:
  - name: pool
    type: object
  - name: enableAzureResourcesDependentTests # Enable tests that are using Azure resources
    type: boolean
    default: false

jobs:
- job: 'Local_JDK'
  pool: ${{ parameters.pool }}
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted VS2017'))
  steps:
  - template: 'java-tool-installer-local-jdk7-steps.yml'