parameters:
  - name: pool
    type: object
jobs:

- job: 'TaskTestViaContainer'
  pool: ${{ parameters.pool }}
  container: node:latest
  steps:
    - template: download-secure-file-steps-lin.yml
    - task: DownloadSecureFile@1
      name: caCertificate
      displayName: 'Download CA certificate'
      inputs:
        secureFile: 'test.js'
    - task: DownloadSecureFile@1
      name: BigFileTest
      displayName: 'Download Big File'
      inputs:
        secureFile: '1.txt'