jobs:
- job: 'Win2019'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2019'
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted Windows 2019 with VS2019'))
  steps:
  - template: nuget-config-steps.yml

- job: 'Win2022'
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  condition: and(succeeded(),  contains(variables.targetPools, 'Windows Server 2022'))
  steps:
  - template: nuget-config-steps.yml

- job: 'MacOS_Public_Catalina'
  pool:
    name: 'LimitedPublicCatalina'
    vmImage: 'macos-10.15'
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted macOS Catalina'))
  steps:
  - template: nuget-config-steps.yml

- job: 'MacOS_Public_BigSur'
  pool:
    name: 'LimitedPublicBigSur'
    vmImage: 'macos-11'
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted macOS BigSur'))
  steps:
  - template: nuget-config-steps.yml

- job: 'MacOS_Public_Monterey'
  pool:
    name: 'LimitedPublicMonterey'
    vmImage: 'macos-12'
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted macOS Monterey'))
  steps:
  - template: nuget-config-steps.yml
