name: $(BuildDefinitionName)_$(Year:yyyy).$(Month).$(DayOfMonth)$(Rev:.r)00

jobs:
- job: 'Nuget_Win2022'
  displayName: Windows2022
  pool:
    name: 'Azure Pipelines'
    vmImage: 'windows-2022'
  condition: and(succeeded(),  contains(variables.targetPools, 'Windows Server 2022'))
  steps:
  - template: nuget-v2-steps.yml

- job: Nuget_VS2019
  displayName: VS2019
  pool: $[ coalesce(variables.windows2019withvs2019, 'Hosted Windows 2019 with VS2019') ]
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted Windows 2019 with VS2019'))
  steps:
  - template: nuget-v2-steps-vs2019.yml
- job: Nuget_VS2019_NoToolInstaller
  displayName: Nuget_VS2019_NoToolInstaller
  pool: $[ coalesce(variables.windows2019withvs2019, 'Hosted Windows 2019 with VS2019') ]
  condition: and(succeeded(),  contains(variables.targetPools, 'Hosted Windows 2019 with VS2019'))
  steps:
  - template: nuget-v2-no-toolinstaller.yml
  
